export const accountNames=["1000 · Cash","1100 · Accounts receivable","1500 · Trucks & equipment","2000 · Accounts payable","2200 · Equipment loans","3000 · Owner’s equity","4000 · Freight revenue","5000 · Fuel expense","5100 · Driver pay","5200 · Repairs & maintenance","5900 · Other expense"] as const;
export type JournalStatus="Draft"|"Posted"|"Reversed";
export type JournalLine={id:string;account:string;description:string;debit:number;credit:number};
export type JournalEntry={id:string;number:string;date:string;memo:string;status:JournalStatus;lines:JournalLine[];postedAt:string;reversalOf:string};
export type JournalDraft=Pick<JournalEntry,"number"|"date"|"memo"|"lines">;
export const demoJournalEntries:JournalEntry[]=[
 {id:"je-1042",number:"JE-1042",date:"2026-09-03",memo:"Record August fuel card statement",status:"Posted",postedAt:"2026-09-03T14:20:00Z",reversalOf:"",lines:[{id:"1",account:"5000 · Fuel expense",description:"August fuel",debit:31284,credit:0},{id:"2",account:"2000 · Accounts payable",description:"Fuel card payable",debit:0,credit:31284}]},
 {id:"je-1041",number:"JE-1041",date:"2026-09-01",memo:"Owner capital contribution",status:"Posted",postedAt:"2026-09-01T09:15:00Z",reversalOf:"",lines:[{id:"3",account:"1000 · Cash",description:"Deposit",debit:25000,credit:0},{id:"4",account:"3000 · Owner’s equity",description:"Capital",debit:0,credit:25000}]},
];
export function journalTotals(lines:JournalLine[]){return lines.reduce((totals,line)=>({debit:totals.debit+line.debit,credit:totals.credit+line.credit}),{debit:0,credit:0})}
export function validateJournal(draft:JournalDraft,entries:JournalEntry[],editingId?:string){const errors:Record<string,string>={};if(!draft.number.trim())errors.number="Journal number is required.";if(entries.some(x=>x.id!==editingId&&x.number.toLowerCase()===draft.number.trim().toLowerCase()))errors.number="Journal number already exists.";if(!draft.date)errors.date="Date is required.";if(!draft.memo.trim())errors.memo="Memo is required.";if(draft.lines.length<2)errors.lines="At least two lines are required.";if(draft.lines.some(x=>!x.account||(x.debit<0||x.credit<0)||(x.debit>0&&x.credit>0)||(x.debit===0&&x.credit===0)))errors.lines="Each line needs one positive debit or credit.";const totals=journalTotals(draft.lines);if(Math.abs(totals.debit-totals.credit)>.005||totals.debit<=0)errors.balance="Debits and credits must be equal and greater than zero.";return errors}
export function reverseJournal(entry:JournalEntry,number:string,date:string):JournalEntry{return{id:crypto.randomUUID(),number,date,memo:`Reversal of ${entry.number}: ${entry.memo}`,status:"Posted",postedAt:new Date().toISOString(),reversalOf:entry.id,lines:entry.lines.map(line=>({...line,id:crypto.randomUUID(),debit:line.credit,credit:line.debit}))}}
