export const vendorBillStatuses=["Draft","Open","Paid","Void"] as const;
export type VendorBillStatus=(typeof vendorBillStatuses)[number];
export const payableExpenseAccounts=["5000 · Fuel expense","5100 · Driver pay","5200 · Repairs & maintenance","5900 · Other expense"] as const;
export const payablePaymentAccounts=["1000 · Cash","1010 · Operating checking","1020 · Savings"] as const;
export type VendorBillPayment={id:string;paidOn:string;amount:number;reference:string;paymentAccount:string;journalNumber:string};
export type VendorBillAdjustmentType="Credit"|"Debit";
export type VendorBillAdjustment={id:string;adjustedOn:string;type:VendorBillAdjustmentType;amount:number;reason:string;journalNumber:string};
export type VendorBill={id:string;vendor:string;billNumber:string;issuedOn:string;dueOn:string;status:VendorBillStatus;amount:number;description:string;expenseAccount:string;journalNumber:string;payments:VendorBillPayment[];adjustments:VendorBillAdjustment[]};
export type VendorBillDraft=Omit<VendorBill,"id"|"payments"|"adjustments"|"journalNumber">&{paidFromAccount:string};
export type VendorBillPaymentDraft={paidOn:string;amount:number;reference:string;paymentAccount:string};
export type VendorBillAdjustmentDraft={adjustedOn:string;type:VendorBillAdjustmentType;amount:number;reason:string};

export const demoVendorBills:VendorBill[]=[
 {id:"bill-1",vendor:"Pilot Travel Center",billNumber:"PILOT-0826",issuedOn:"2026-08-25",dueOn:"2026-09-24",status:"Open",amount:2480,description:"August fuel card statement",expenseAccount:"5000 · Fuel expense",journalNumber:"JE-1042",payments:[],adjustments:[]},
 {id:"bill-2",vendor:"Martin Fleet Services",billNumber:"MFS-4412",issuedOn:"2026-08-03",dueOn:"2026-09-02",status:"Paid",amount:1285,description:"Unit 118 service",expenseAccount:"5200 · Repairs & maintenance",journalNumber:"JE-1036",payments:[{id:"payment-1",paidOn:"2026-09-02",amount:1285,reference:"ACH 8841",paymentAccount:"1010 · Operating checking",journalNumber:"JE-1041"}],adjustments:[]},
];

const money=(value:number)=>{const cents=Math.round(value*100);if(!Number.isSafeInteger(cents))throw new Error("Amount is invalid or too large.");return cents};
export function billBalance(bill:Pick<VendorBill,"status"|"amount"|"payments"|"adjustments">){if(bill.status==="Draft"||bill.status==="Void")return 0;const adjusted=money(bill.amount)+bill.adjustments.reduce((total,item)=>total+(item.type==="Debit"?money(item.amount):-money(item.amount)),0);return(adjusted-bill.payments.reduce((total,payment)=>total+money(payment.amount),0))/100}
export function billOutstanding(bill:Pick<VendorBill,"status"|"amount"|"payments"|"adjustments">){return Math.max(0,billBalance(bill))}
export function billVendorCredit(bill:Pick<VendorBill,"status"|"amount"|"payments"|"adjustments">){return Math.max(0,-billBalance(bill))}
export function validateVendorBill(draft:VendorBillDraft){const errors:Record<string,string>={};if(!draft.vendor.trim())errors.vendor="Enter a vendor.";if(!draft.billNumber.trim())errors.billNumber="Enter the vendor bill number.";if(!draft.issuedOn)errors.issuedOn="Choose an issue date.";if(!draft.dueOn)errors.dueOn="Choose a due date.";if(draft.issuedOn&&draft.dueOn<draft.issuedOn)errors.dueOn="Due date cannot be before the issue date.";if(!Number.isFinite(draft.amount)||draft.amount<=0)errors.amount="Amount must be greater than zero.";if(!draft.expenseAccount.trim())errors.expenseAccount="Choose an expense account.";if(draft.status==="Paid"&&!draft.paidFromAccount.trim())errors.paidFromAccount="Choose the payment account.";return errors}
export function validateVendorBillPayment(draft:VendorBillPaymentDraft,outstanding:number){const errors:Record<string,string>={};if(!draft.paidOn)errors.paidOn="Choose a payment date.";if(!Number.isFinite(draft.amount)||draft.amount<=0)errors.amount="Payment must be greater than zero.";else if(Math.round(draft.amount*100)>Math.round(outstanding*100))errors.amount="Payment cannot exceed the outstanding balance.";if(!draft.paymentAccount.trim())errors.paymentAccount="Choose the payment account.";return errors}
export function validateVendorBillAdjustment(draft:VendorBillAdjustmentDraft,adjustedTotal:number,billDate?:string){const errors:Record<string,string>={};if(!draft.adjustedOn)errors.adjustedOn="Choose an adjustment date.";else if(billDate&&draft.adjustedOn<billDate)errors.adjustedOn="Adjustment date cannot precede the bill date.";if(!["Credit","Debit"].includes(draft.type))errors.type="Choose credit or debit.";if(!Number.isFinite(draft.amount)||draft.amount<=0)errors.amount="Adjustment must be greater than zero.";else if(draft.type==="Credit"&&money(draft.amount)>money(adjustedTotal))errors.amount="Credit cannot exceed the adjusted bill total.";if(!draft.reason.trim())errors.reason="Enter a reason for the adjustment.";return errors}
export function filterVendorBills(bills:VendorBill[],query:string,status:string){const term=query.trim().toLowerCase();return bills.filter(bill=>(status==="All statuses"||bill.status===status)&&(!term||[bill.vendor,bill.billNumber,bill.description].some(value=>value.toLowerCase().includes(term))))}
