"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CalendarClock,CheckCircle2,Pencil,Search,Trash2,Wrench,X} from "lucide-react";
import {demoWorkOrders,maintenanceSummary,nextWorkOrderStatus,serviceTypes,validateWorkOrder,WorkOrder,WorkOrderDraft,workOrderStatuses} from "@/lib/maintenance";
import {deleteWorkOrder,listWorkOrders,saveWorkOrder} from "@/app/actions/maintenance";

const storageKey="kings-maintenance-v1";
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const blank=():WorkOrderDraft=>({reference:`WO-${Math.floor(1053+Math.random()*8000)}`,unit:"",serviceType:"Preventive maintenance",description:"",vendor:"",scheduledDate:new Date().toISOString().slice(0,10),odometer:0,estimatedCost:0,actualCost:0,status:"Scheduled",completedDate:""});

export function MaintenanceWorkspace({openCreate,onCreateClosed,companyId}:{openCreate:boolean;onCreateClosed:()=>void;companyId?:string}){
  const [records,setRecords]=useState<WorkOrder[]>(companyId?[]:demoWorkOrders),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(""),[status,setStatus]=useState("Open"),[editing,setEditing]=useState<WorkOrder|null>(null),[error,setError]=useState("");
  useEffect(()=>{if(companyId){listWorkOrders(companyId).then(setRecords).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load work orders.")).finally(()=>setLoaded(true));return}try{const saved=localStorage.getItem(storageKey);if(saved)setRecords(JSON.parse(saved) as WorkOrder[])}catch{}setLoaded(true)},[companyId]);
  useEffect(()=>{if(loaded&&!companyId)localStorage.setItem(storageKey,JSON.stringify(records))},[loaded,records,companyId]);
  const summary=useMemo(()=>maintenanceSummary(records),[records]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return records.filter(item=>(status==="All"||(status==="Open"?(item.status==="Scheduled"||item.status==="In progress"):item.status===status))&&(!q||`${item.reference} ${item.unit} ${item.description} ${item.vendor}`.toLowerCase().includes(q)))},[records,query,status]);
  async function save(draft:WorkOrderDraft,id?:string){try{setError("");const saved=companyId?await saveWorkOrder(companyId,draft,records,id):{...draft,id:id??crypto.randomUUID()};setRecords(current=>id?current.map(item=>item.id===id?saved:item):[saved,...current]);setEditing(null);onCreateClosed()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save work order.")}}
  async function advance(item:WorkOrder){const next=nextWorkOrderStatus(item.status);if(!next)return;const draft={...item,status:next,completedDate:next==="Completed"?new Date().toISOString().slice(0,10):item.completedDate,actualCost:next==="Completed"&&item.actualCost===0?item.estimatedCost:item.actualCost};await save(draft,item.id)}
  async function remove(item:WorkOrder){if(confirm(`Delete work order ${item.reference}?`))try{if(companyId)await deleteWorkOrder(companyId,item.id);setRecords(current=>current.filter(row=>row.id!==item.id))}catch(cause){setError(cause instanceof Error?cause.message:"Unable to delete work order.")}}
  const summaryCards=[{label:"Open work orders",value:summary.open,Icon:CalendarClock},{label:"In progress",value:summary.inProgress,Icon:Wrench},{label:"Completed",value:summary.completed,Icon:CheckCircle2},{label:"Completed cost",value:money.format(summary.actualCost),Icon:CheckCircle2}];
  return <>{error&&<div role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summaryCards.map(({label,value,Icon})=><div className="card p-4" key={label}><div className="flex items-center justify-between"><span className="text-xs font-bold text-[var(--muted)]">{label}</span><Icon className="text-[var(--teal)]" size={17}/></div><p className="display mt-2 text-2xl font-extrabold text-[var(--navy)]">{value}</p></div>)}</div>
  <div className="mt-4 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-white py-2.5 pl-10 pr-3 text-sm" placeholder="Search work order, unit, vendor…"/></div><select aria-label="Filter work orders" value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border border-[var(--line)] bg-white px-3 py-2.5 text-sm font-bold">{["Open","All",...workOrderStatuses].map(option=><option key={option}>{option}</option>)}</select></div>
  <div className="card mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="bg-[var(--canvas)] text-xs uppercase tracking-wider text-[var(--muted)]"><th className="px-5 py-3">Work order</th><th>Unit / service</th><th>Scheduled</th><th>Vendor</th><th className="text-right">Cost</th><th className="px-5 text-right">Status / actions</th></tr></thead><tbody>{visible.map(item=>{const next=nextWorkOrderStatus(item.status);return <tr key={item.id} className="border-t border-[var(--line)]"><td className="px-5 py-4"><b className="text-sm text-[var(--navy)]">{item.reference}</b><p className="max-w-56 truncate text-xs text-[var(--muted)]">{item.description}</p></td><td><b className="text-sm">Unit {item.unit}</b><p className="text-xs text-[var(--muted)]">{item.serviceType}</p></td><td className="text-sm">{new Date(`${item.scheduledDate}T00:00:00`).toLocaleDateString()}</td><td className="text-sm">{item.vendor||"—"}</td><td className="text-right text-sm font-bold">{money.format(item.status==="Completed"?item.actualCost:item.estimatedCost)}</td><td className="px-5"><div className="flex items-center justify-end gap-1"><span className={`pill mr-2 ${item.status==="Completed"?"bg-[#e8f5ee] text-[#287250]":item.status==="In progress"?"bg-[#fff8e4] text-[#9a6c1d]":item.status==="Cancelled"?"bg-red-50 text-red-700":"bg-[var(--teal-light)] text-[var(--teal)]"}`}>{item.status}</span>{next&&<button onClick={()=>advance(item)} title={`Mark ${next.toLowerCase()}`} className="rounded-lg p-2 text-[var(--teal)] hover:bg-[var(--teal-light)]"><CheckCircle2 size={17}/></button>}<button onClick={()=>setEditing(item)} title="Edit" className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--canvas)]"><Pencil size={16}/></button><button onClick={()=>remove(item)} title="Delete" className="rounded-lg p-2 text-[var(--muted)] hover:text-red-600"><Trash2 size={16}/></button></div></td></tr>})}{visible.length===0&&<tr><td colSpan={6} className="p-10 text-center text-sm text-[var(--muted)]">No work orders match this view.</td></tr>}</tbody></table></div></div>
  {(openCreate||editing)&&<WorkOrderForm record={editing} records={records} onCancel={()=>{setEditing(null);onCreateClosed()}} onSave={save}/>}</>;
}

function WorkOrderForm({record,records,onCancel,onSave}:{record:WorkOrder|null;records:WorkOrder[];onCancel:()=>void;onSave:(draft:WorkOrderDraft,id?:string)=>void}){
  const [draft,setDraft]=useState<WorkOrderDraft>(record?{reference:record.reference,unit:record.unit,serviceType:record.serviceType,description:record.description,vendor:record.vendor,scheduledDate:record.scheduledDate,odometer:record.odometer,estimatedCost:record.estimatedCost,actualCost:record.actualCost,status:record.status,completedDate:record.completedDate}:blank),[errors,setErrors]=useState<Record<string,string>>({});
  function patch(value:Partial<WorkOrderDraft>){setDraft(current=>({...current,...value}))}function submit(event:FormEvent){event.preventDefault();const found=validateWorkOrder(draft,records,record?.id);setErrors(found);if(!Object.keys(found).length)onSave(draft,record?.id)}
  const input=(name:keyof WorkOrderDraft,label:string,type="text")=><label className="text-xs font-bold">{label}<input type={type} value={draft[name]} onChange={event=>patch({[name]:type==="number"?Number(event.target.value):event.target.value})} className="input"/>{errors[name]&&<span className="mt-1 block text-red-600">{errors[name]}</span>}</label>;
  return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onCancel}><form onSubmit={submit} onMouseDown={event=>event.stopPropagation()} className="max-h-[95vh] w-full overflow-y-auto rounded-t-3xl bg-white p-6 sm:max-w-2xl sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-bold text-[var(--teal)]">Fleet health</p><h2 className="display text-2xl font-extrabold">{record?`Edit ${record.reference}`:"New work order"}</h2></div><button type="button" aria-label="Close work order form" onClick={onCancel} className="rounded-xl border border-[var(--line)] p-2"><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{input("reference","Reference")}{input("unit","Unit number")}<label className="text-xs font-bold">Service type<select value={draft.serviceType} onChange={event=>patch({serviceType:event.target.value as WorkOrderDraft["serviceType"]})} className="input">{serviceTypes.map(value=><option key={value}>{value}</option>)}</select></label>{input("scheduledDate","Scheduled date","date")}<label className="text-xs font-bold sm:col-span-2">Description<textarea value={draft.description} onChange={event=>patch({description:event.target.value})} className="input min-h-20"/>{errors.description&&<span className="text-red-600">{errors.description}</span>}</label>{input("vendor","Vendor")}{input("odometer","Odometer","number")}{input("estimatedCost","Estimated cost","number")}{input("actualCost","Actual cost","number")}<label className="text-xs font-bold">Status<select value={draft.status} onChange={event=>patch({status:event.target.value as WorkOrderDraft["status"]})} className="input">{workOrderStatuses.map(value=><option key={value}>{value}</option>)}</select></label>{input("completedDate","Completion date","date")}{errors.cost&&<p className="text-xs text-red-600 sm:col-span-2">{errors.cost}</p>}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl border border-[var(--line)] px-4 py-3 text-sm font-bold">Cancel</button><button className="rounded-xl bg-[var(--teal)] px-5 py-3 text-sm font-bold text-white">Save work order</button></div></form></div>;
}
