"use client";
import {useEffect,useState} from "react";
import {listLedgerAccounts,listAccountingPeriods,saveLedgerAccount,setAccountingPeriod,type LedgerAccount,type AccountingPeriod} from "@/app/actions/finance-admin";
export function AccountingAdmin({companyId,onChange}:{companyId:string;onChange:()=>void}){
 const [accounts,setAccounts]=useState<LedgerAccount[]>([]),[periods,setPeriods]=useState<AccountingPeriod[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 const [number,setNumber]=useState(""),[name,setName]=useState(""),[type,setType]=useState("expense"),[start,setStart]=useState(""),[end,setEnd]=useState("");
 useEffect(()=>{let active=true;Promise.all([listLedgerAccounts(companyId),listAccountingPeriods(companyId)]).then(([a,p])=>{if(active){setAccounts(a);setPeriods(p)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[companyId,reload]);
 async function run(action:()=>Promise<void>){setBusy(true);setError("");try{await action();setReload(x=>x+1);onChange()}catch(e){setError(e instanceof Error?e.message:"Unable to save accounting settings.")}finally{setBusy(false)}}
 return <section className="card mt-6 p-5"><h2 className="text-xl font-extrabold">Accounts and accounting periods</h2><p className="mt-1 text-sm text-[var(--muted)]">Finance staff manage accounts. Owners and administrators can close or reopen completed periods. Used account numbers and types stay fixed.</p>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}<form className="mt-4 grid gap-3 sm:grid-cols-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await saveLedgerAccount(companyId,{number,name,type,active:true});setNumber("");setName("")})}}><label>Account number<input className="input" required value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Account name<input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label>Account type<select className="input" value={type} onChange={e=>setType(e.target.value)}>{["asset","liability","equity","income","expense"].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy} className="rounded-xl bg-[var(--teal)] p-3 font-bold text-white">Add account</button></form><div className="mt-4 max-h-72 overflow-auto">{accounts.map(a=><div key={a.id} className="flex items-center justify-between gap-3 border-t py-2"><span>{a.number} · {a.name} <small>({a.type})</small></span><button disabled={busy} onClick={()=>void run(()=>saveLedgerAccount(companyId,{...a,active:!a.active},a.id))} className="rounded-lg border px-3 py-1">{a.active?"Deactivate":"Activate"}</button></div>)}</div><form className="mt-6 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void run(()=>setAccountingPeriod(companyId,start,end,true))}}><label>Period start<input required type="date" className="input" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end<input required type="date" className="input" value={end} onChange={e=>setEnd(e.target.value)}/></label><button disabled={busy} className="rounded-xl border p-3 font-bold">Close period</button></form><div className="mt-3">{periods.map(p=><div key={p.id} className="flex items-center justify-between border-t py-2"><span>{p.start} – {p.end} · {p.closed?"Closed":"Open"}</span><button disabled={busy} className="rounded-lg border px-3 py-1" onClick={()=>void run(()=>setAccountingPeriod(companyId,p.start,p.end,!p.closed))}>{p.closed?"Reopen":"Close"}</button></div>)}</div></section>
}
