import {act,createElement} from "react";
import {createRoot,type Root} from "react-dom/client";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
const {recognize}=vi.hoisted(()=>({recognize:vi.fn()}));
vi.mock("@/lib/receipt-ocr",()=>({recognizeReceipt:recognize}));
import {ReceiptScanner} from "@/components/receipts/receipt-scanner";
let container:HTMLDivElement,root:Root;const apply=vi.fn(),onFile=vi.fn(),onBusy=vi.fn();
const button=(name:string)=>Array.from(container.querySelectorAll("button")).find(b=>b.textContent===name)!;
async function select(file:File){const input=container.querySelector<HTMLInputElement>('[aria-label="Choose receipt photo for auto-fill"]')!;Object.defineProperty(input,"files",{configurable:true,value:[file]});await act(async()=>input.dispatchEvent(new Event("change",{bubbles:true})))}
beforeEach(async()=>{vi.clearAllMocks();(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;vi.stubGlobal("URL",class extends URL {static createObjectURL=()=>"blob:receipt";static revokeObjectURL=vi.fn()});container=document.createElement("div");document.body.append(container);root=createRoot(container);await act(async()=>root.render(createElement(ReceiptScanner,{onApply:apply,onFile,onBusyChange:onBusy,fileHelp:"Photo attaches after saving."})))});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.unstubAllGlobals()});
it("requires review before applying extracted values",async()=>{recognize.mockResolvedValue({suggestions:{vendor:"Pilot",date:"2026-09-09",totalCost:40,gallons:10},text:"Pilot TOTAL 40.00",warnings:[]});const file=new File(["photo"],"gas.jpg",{type:"image/jpeg"});await select(file);expect(apply).not.toHaveBeenCalled();expect(onFile).toHaveBeenCalledWith(file);expect(container.textContent).toContain("Review suggestions");await act(async()=>button("Apply suggestions").click());expect(apply).toHaveBeenCalledWith({vendor:"Pilot",date:"2026-09-09",totalCost:40,gallons:10})});
it("does not run recognition for unsupported files",async()=>{await select(new File(["pdf"],"gas.pdf",{type:"application/pdf"}));expect(recognize).not.toHaveBeenCalled();expect(container.querySelector('[role="alert"]')?.textContent).toContain("PDFs can still be attached")});
it("ignores a cancelled reading after its photo has been removed",async()=>{let resolve!:(result:unknown)=>void;recognize.mockReturnValue(new Promise(r=>{resolve=r}));await select(new File(["photo"],"gas.jpg",{type:"image/jpeg"}));await act(async()=>button("Remove photo").click());expect(recognize.mock.calls[0][2].aborted).toBe(true);await act(async()=>resolve({suggestions:{vendor:"Old photo"},text:"old",warnings:[]}));expect(container.textContent).not.toContain("Review suggestions");expect(apply).not.toHaveBeenCalled();expect(onFile).toHaveBeenLastCalledWith(null)});
it("shows recognition failures and leaves manual entry available",async()=>{recognize.mockRejectedValue(new Error("Reader unavailable"));await select(new File(["photo"],"gas.jpg",{type:"image/jpeg"}));expect(container.querySelector('[role="alert"]')?.textContent).toBe("Reader unavailable");expect(button("Upload photo to auto-fill").disabled).toBe(false);expect(onBusy).toHaveBeenLastCalledWith(false)});
