"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Camera, Check, Download, FileSpreadsheet, Fuel, Plus, Search, ShieldCheck, Upload, Wrench } from "lucide-react";
import { TransactionWorkspace } from "@/components/transactions/transaction-workspace";
import { InvoiceWorkspace } from "@/components/invoices/invoice-workspace";
import { LoadWorkspace } from "@/components/operations/load-workspace";
import { FleetWorkspace } from "@/components/fleet/fleet-workspace";
import { AssistantWorkspace } from "@/components/assistant/assistant-workspace";

const moduleCopy:Record<string,{eyebrow:string;title:string;description:string;action:string}> = {
  Transactions:{eyebrow:"Money movement",title:"Income & expenses",description:"Review, categorize, split, match, and approve every transaction.",action:"Add transaction"},
  Invoices:{eyebrow:"Accounts receivable",title:"Invoices & payments",description:"Send polished invoices and keep every payment accounted for.",action:"New invoice"},
  "Loads & routes":{eyebrow:"Dispatch",title:"Loads & routes",description:"Coordinate each shipment from pickup appointment to proof of delivery.",action:"Create load"},
  Fleet:{eyebrow:"Equipment",title:"Fleet command",description:"Keep trucks, trailers, documents, and utilization in one place.",action:"Add vehicle"},
  "Fuel & mileage":{eyebrow:"Operating costs",title:"Fuel & mileage",description:"Understand MPG, cost per mile, and every mile driven.",action:"Record fuel"},
  Maintenance:{eyebrow:"Fleet health",title:"Maintenance",description:"Plan service, manage work orders, and reduce costly downtime.",action:"New work order"},
  Payroll:{eyebrow:"People",title:"Payroll & settlements",description:"Prepare accurate pay records without filing payroll taxes automatically.",action:"Start pay run"},
  Accounting:{eyebrow:"General ledger",title:"Accounting",description:"Double-entry books with locked posted entries and traceable corrections.",action:"Journal entry"},
  Reports:{eyebrow:"Business intelligence",title:"Reports",description:"Financial statements and operational insight, ready for your accountant.",action:"Export report"},
  Approvals:{eyebrow:"Review queue",title:"Approvals",description:"Resolve driver submissions, expenses, documents, and exceptions.",action:"Review next"},
  "Team & roles":{eyebrow:"Access control",title:"Team & roles",description:"Give each person exactly the access their work requires.",action:"Invite person"},
  "Audit log":{eyebrow:"Accountability",title:"Audit history",description:"A durable timeline of sensitive actions and financial changes.",action:"Export log"},
  Settings:{eyebrow:"Company administration",title:"Settings",description:"Manage companies, categories, yearly rates, integrations, and preferences.",action:"Save changes"},
  "AI assistant":{eyebrow:"OpenAI powered",title:"Accounting assistant",description:"Get practical help with bookkeeping workflows and trucking operations.",action:"Ask a question"},
};

export function ModuleView({module,openForm=false,assistantEnabled=false}:{module:string;openForm?:boolean;assistantEnabled?:boolean}) {
  const copy=moduleCopy[module]??moduleCopy.Transactions;
  const [showForm,setShowForm]=useState(openForm);
  return <div className="mx-auto max-w-[1600px] p-4 md:p-7 xl:p-9">
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-sm font-bold text-[var(--teal)]">{copy.eyebrow}</p><h1 className="display text-3xl font-extrabold text-[var(--navy)] md:text-4xl">{copy.title}</h1><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">{copy.description}</p></div>{module!=="AI assistant"&&<button onClick={()=>setShowForm(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[var(--teal)] px-4 py-3 text-sm font-bold text-white"><Plus size={18}/>{copy.action}</button>}</div>
    {module==="AI assistant"?<AssistantWorkspace enabled={assistantEnabled}/>:module==="Loads & routes"?<LoadWorkspace openCreate={showForm} onCreateClosed={()=>setShowForm(false)}/>:module==="Fleet"?<FleetWorkspace openCreate={showForm} onCreateClosed={()=>setShowForm(false)}/>:module==="Fuel & mileage"?<FuelMileage/>:module==="Reports"?<Reports/>:module==="Team & roles"?<Team/>:module==="Transactions"?<TransactionWorkspace openCreate={showForm} onCreateClosed={()=>setShowForm(false)}/>:module==="Invoices"?<InvoiceWorkspace openCreate={showForm} onCreateClosed={()=>setShowForm(false)}/>:<Generic module={module}/>}
    {showForm&&!(["Transactions","Invoices","Loads & routes","Fleet","AI assistant"].includes(module))&&<QuickForm title={copy.action} module={module} onClose={()=>setShowForm(false)}/>}
  </div>;
}

function Toolbar(){return <div className="flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]"/><input disabled aria-label="Search records" className="w-full rounded-xl border border-[var(--line)] bg-[var(--canvas)] py-2.5 pl-10 pr-3 text-sm" placeholder="Search coming in this module…"/></div><button disabled className="flex cursor-not-allowed items-center gap-2 rounded-xl border border-[var(--line)] bg-white px-3.5 text-sm font-bold opacity-45"><Download size={16}/>Export</button></div>}
function FuelMileage(){return <div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><div><Toolbar/><div className="card mt-4 p-5"><h2 className="display text-xl font-extrabold">Recent fuel entries</h2>{["Pilot · Dallas, TX","Love’s · Memphis, TN","TA · Macon, GA","Shell · Tampa, FL"].map((x,i)=><div className="flex items-center gap-3 border-b border-[var(--line)] py-4 last:border-0" key={x}><div className="grid size-10 place-items-center rounded-xl bg-[#fff8e4] text-[#b07d22]"><Fuel size={18}/></div><div className="flex-1"><b className="text-sm">{x}</b><p className="text-xs text-[var(--muted)]">Unit {204+i} · {116+i*8}.4 gallons</p></div><b>${(485+i*48).toFixed(2)}</b></div>)}</div></div><div className="card p-5"><h2 className="display text-xl font-extrabold">Mileage check</h2><p className="mt-1 text-sm text-[var(--muted)]">Enter odometer readings</p><MileageCalculator/></div></div>}
function MileageCalculator(){const [start,setStart]=useState("168240");const [end,setEnd]=useState("169082");const total=useMemo(()=>Math.max(0,Number(end)-Number(start)),[start,end]);return <div className="mt-5 space-y-4"><label className="block text-xs font-bold">Starting odometer<input value={start} onChange={e=>setStart(e.target.value)} inputMode="numeric" className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3 text-base"/></label><label className="block text-xs font-bold">Ending odometer<input value={end} onChange={e=>setEnd(e.target.value)} inputMode="numeric" className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3 text-base"/></label><div className="rounded-2xl bg-[var(--navy)] p-5 text-white"><p className="text-xs text-white/60">Calculated trip mileage</p><p className="display mt-1 text-3xl font-extrabold">{total.toLocaleString()} mi</p></div></div>}
function Reports(){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{["Profit & loss","Balance sheet","Cash flow","General ledger","Trial balance","A/R aging","A/P aging","Profit by truck","Profit by driver","Cost per mile","Fuel summary","Year-end package"].map((name)=><button className="card group flex items-center gap-4 p-5 text-left hover:border-[var(--teal)]" key={name}><div className="grid size-11 place-items-center rounded-xl bg-[var(--teal-light)] text-[var(--teal)]"><FileSpreadsheet size={20}/></div><span className="flex-1 font-extrabold text-[var(--navy)]">{name}</span><ArrowRight className="text-[var(--muted)] group-hover:text-[var(--teal)]" size={18}/></button>)}</div>}
function Team(){return <><Toolbar/><div className="card mt-4 overflow-hidden">{[["Kendra Williams","Owner","KW"],["Andre Cole","Accountant","AC"],["Maya Chen","Dispatcher","MC"],["Marcus Hill","Driver","MH"],["Dana Brooks","Driver","DB"]].map(([name,role,initials])=><div className="flex items-center gap-3 border-b border-[var(--line)] p-4 last:border-0 md:px-6" key={name}><div className="grid size-10 place-items-center rounded-full bg-[var(--navy)] text-xs font-extrabold text-white">{initials}</div><div className="flex-1"><b>{name}</b><p className="text-xs text-[var(--muted)]">{name.toLowerCase().replace(" ",".")}@example.com</p></div><span className="pill bg-[var(--teal-light)] text-[var(--teal)]">{role}</span><span className="hidden text-xs font-semibold text-[var(--muted)] sm:block">Active</span></div>)}</div></>}
function Generic({module}:{module:string}){const cards=module==="Maintenance"?["Oil change · Unit 118","Annual inspection · Unit 204","Tire replacement · Unit 221"]:module==="Payroll"?["Sep 1–15 pay period","Driver settlements","Contractor payments"]:module==="Approvals"?["Receipt #0841","Fuel entry · Marcus Hill","Mileage log · Dana Brooks"]:["Company configuration","Category mapping","Integration status"];return <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section className="card p-5 md:p-6"><h2 className="display text-xl font-extrabold">{module} workspace</h2><div className="mt-4">{cards.map((x)=><button className="flex w-full items-center gap-3 border-b border-[var(--line)] py-4 text-left last:border-0" key={x}><div className="grid size-10 place-items-center rounded-xl bg-[var(--teal-light)] text-[var(--teal)]">{module==="Maintenance"?<Wrench size={18}/>:module==="Approvals"?<Check size={18}/>:<ShieldCheck size={18}/>}</div><div className="flex-1"><b className="text-sm">{x}</b><p className="text-xs text-[var(--muted)]">Updated today · King’s Transport LLC</p></div><ArrowRight size={17}/></button>)}</div></section><aside className="card p-6"><h2 className="display text-xl font-extrabold">At a glance</h2><div className="mt-5 rounded-2xl bg-[var(--navy)] p-5 text-white"><p className="text-sm text-white/65">Items requiring attention</p><p className="display mt-2 text-4xl font-extrabold">{module==="Approvals"?"8":"3"}</p><p className="mt-4 text-xs text-white/55">All activity is protected by company access controls and recorded in the audit log.</p></div></aside></div>}

function QuickForm({title,module,onClose}:{title:string;module:string;onClose:()=>void}){return <div className="fixed inset-0 z-[60] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onClose}><form onSubmit={e=>{e.preventDefault();onClose()}} onMouseDown={e=>e.stopPropagation()} className="w-full rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-lg sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[var(--teal)]">King’s Transport LLC</p><h2 className="display text-2xl font-extrabold text-[var(--navy)]">{title}</h2></div><button type="button" onClick={onClose} className="rounded-xl border border-[var(--line)] px-3 py-2">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Reference<input required className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3" placeholder={`${module} reference`}/></label><label className="text-xs font-bold">Date<input type="date" required className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3"/></label><label className="text-xs font-bold sm:col-span-2">Description<input required className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3" placeholder="Add helpful details"/></label><label className="text-xs font-bold">Amount<input type="number" step="0.01" className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3" placeholder="0.00"/></label><label className="text-xs font-bold">Status<select className="mt-1.5 w-full rounded-xl border border-[var(--line)] p-3"><option>Draft</option><option>Ready for review</option><option>Approved</option></select></label></div><button type="button" className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[var(--teal)] bg-[var(--teal-light)] p-4 text-sm font-bold text-[var(--teal)]">{module==="Transactions"?<Camera size={18}/>:<Upload size={18}/>} Attach supporting document</button><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-[var(--line)] px-4 py-3 text-sm font-bold">Cancel</button><button className="rounded-xl bg-[var(--teal)] px-5 py-3 text-sm font-bold text-white">Save draft</button></div></form></div>}
