"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, LockKeyhole, Truck } from "lucide-react";
import { createClient } from "@/lib/supabase/browser";
import { useRouter } from "next/navigation";

export default function LoginPage(){
  const router=useRouter();
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);const supabase=createClient();if(!supabase){setMessage("Demo mode: connect Supabase in .env.local to sign in.");setBusy(false);return;}const {error}=await supabase.auth.signInWithPassword({email:String(data.get("email")),password:String(data.get("password"))});setMessage(error?.message??"Signed in successfully.");setBusy(false);if(!error)router.push("/workspace");}
  return <main className="min-h-screen bg-[var(--navy)] p-4 sm:grid sm:place-items-center"><div className="grid w-full max-w-5xl overflow-hidden rounded-3xl bg-white shadow-2xl lg:grid-cols-[1.05fr_1fr]">
    <section className="hidden bg-[#0f3a49] p-12 text-white lg:flex lg:flex-col"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[var(--gold)] text-xl font-black text-[var(--navy)]">K</div><div className="display text-xl font-extrabold">King’s Accounting</div></div><div className="my-auto"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#69cfbf]">Built for the road</p><h1 className="display mt-4 text-4xl font-extrabold leading-tight">Know your numbers.<br/>Run a stronger fleet.</h1><p className="mt-5 max-w-md text-white/65">Books, dispatch, drivers, documents, and fleet costs in one secure workspace.</p><div className="mt-9 space-y-4">{["Company-separated financial data","Private documents and receipts","Fine-grained team permissions"].map(x=><div className="flex items-center gap-3 text-sm font-semibold" key={x}><CheckCircle2 className="text-[#69cfbf]" size={19}/>{x}</div>)}</div></div><div className="flex items-center gap-2 text-xs text-white/45"><Truck size={16}/>Purpose-built for trucking businesses</div></section>
    <section className="p-7 sm:p-12"><div className="mb-9 lg:hidden"><div className="display text-xl font-extrabold text-[var(--navy)]">King’s Accounting</div></div><div className="grid size-12 place-items-center rounded-2xl bg-[var(--teal-light)] text-[var(--teal)]"><LockKeyhole/></div><h2 className="display mt-6 text-3xl font-extrabold text-[var(--navy)]">Welcome back</h2><p className="mt-2 text-sm text-[var(--muted)]">Sign in to your company workspace.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-bold">Email address<input name="email" required type="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-[var(--line)] p-3" placeholder="you@company.com"/></label><label className="block text-sm font-bold">Password<input name="password" required type="password" autoComplete="current-password" className="mt-2 w-full rounded-xl border border-[var(--line)] p-3" placeholder="••••••••"/></label>{message&&<p role="status" className="rounded-xl bg-[var(--canvas)] p-3 text-sm">{message}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--teal)] p-3.5 font-bold text-white disabled:opacity-50">{busy?"Signing in…":"Sign in"}<ArrowRight size={18}/></button></form><Link href="/" className="mt-5 block text-center text-sm font-bold text-[var(--teal)]">Explore the demo workspace</Link></section>
  </div></main>
}
