"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {Building2,CheckCircle2,FileUp,Link2,RefreshCw} from "lucide-react";
import {completeBankReconciliation,createBankAccount,importBankStatement,listBankingWorkspace,reviewBankTransaction,saveBankReconciliation} from "@/app/actions/banking";
import {BankingWorkspaceData,reconciliationDifference} from "@/lib/banking";

const empty:BankingWorkspaceData={accounts:[],ledgerAccounts:[],transactions:[],candidates:[],reconciliations:[],imports:[]};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const today=new Date().toISOString().slice(0,10);

export function BankReconciliationWorkspace({companyId}:{companyId:string}){
  const[data,setData]=useState(empty),[accountId,setAccountId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const[selectedMatches,setSelectedMatches]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{setBusy(true);setError("");try{const next=await listBankingWorkspace(companyId);setData(next);setAccountId(current=>current&&next.accounts.some(x=>x.id===current)?current:next.accounts[0]?.id??"")}catch(cause){setError(message(cause))}finally{setBusy(false)}},[companyId]);
  useEffect(()=>{void load()},[load]);
  const rows=useMemo(()=>data.transactions.filter(x=>x.bankAccountId===accountId),[data.transactions,accountId]);
  const reconciliations=useMemo(()=>data.reconciliations.filter(x=>x.bankAccountId===accountId),[data.reconciliations,accountId]);
  async function run(task:()=>Promise<unknown>,success:string){setBusy(true);setError("");setNotice("");try{await task();setNotice(success);await load()}catch(cause){setError(message(cause));setBusy(false)}}
  async function addAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>createBankAccount(companyId,String(form.get("name")),String(form.get("type")),String(form.get("ledger"))),"Bank account linked to the ledger.")}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);form.set("bankAccountId",accountId);setBusy(true);setError("");setNotice("");try{const result=await importBankStatement(companyId,form);await load();setNotice(`${result.importedCount} imported; ${result.duplicateCount} duplicate${result.duplicateCount===1?"":"s"} skipped.`)}catch(cause){setError(message(cause));setBusy(false)}}
  async function reconcile(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>saveBankReconciliation(companyId,accountId,String(form.get("startsOn")),String(form.get("endsOn")),Number(form.get("balance"))),"Draft reconciliation calculated.")}
  return <section className="mt-8" aria-labelledby="bank-reconciliation-title">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--teal)]">Banking</p><h2 id="bank-reconciliation-title" className="display text-2xl font-extrabold text-[var(--navy)]">Statement reconciliation</h2><p className="mt-1 text-sm text-[var(--muted)]">Import signed bank activity, match it to posted journals, and lock balanced statement periods.</p></div><button onClick={()=>void load()} disabled={busy} className="flex items-center gap-2 rounded-xl border border-[var(--line)] bg-white px-3 py-2 text-sm font-bold disabled:opacity-50"><RefreshCw size={16}/>Refresh</button></div>
    {error?<p role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}{notice?<p role="status" className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>:null}{busy?<p role="status" className="mt-2 text-xs font-bold text-[var(--teal)]">Updating bank workspace…</p>:null}
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><form onSubmit={addAccount} className="card p-5"><div className="flex items-center gap-2 font-extrabold text-[var(--navy)]"><Building2 size={18}/>Link a bank ledger</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Account name<input required name="name" maxLength={120} className="input" placeholder="Operating checking"/></label><label className="text-xs font-bold">Bank type<select name="type" className="input"><option value="checking">Checking</option><option value="savings">Savings</option></select></label><label className="text-xs font-bold sm:col-span-2">Asset ledger account<select required name="ledger" className="input" defaultValue=""><option value="" disabled>Select an account</option>{data.ledgerAccounts.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label></div><button disabled={busy||!data.ledgerAccounts.length} className="mt-4 rounded-xl bg-[var(--navy)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-45">Link account</button></form>
      <form onSubmit={upload} className="card p-5"><div className="flex items-center gap-2 font-extrabold text-[var(--navy)]"><FileUp size={18}/>Import statement CSV</div><label className="mt-4 block text-xs font-bold">Bank account<select aria-label="Bank account" value={accountId} onChange={event=>setAccountId(event.target.value)} className="input"><option value="">Select an account</option>{data.accounts.map(x=><option key={x.id} value={x.id}>{x.name} · {x.ledgerAccount}</option>)}</select></label><label className="mt-3 block text-xs font-bold">CSV statement<input required name="statement" type="file" accept=".csv,text/csv" className="input file:mr-3 file:rounded-lg file:border-0 file:bg-[var(--teal-light)] file:px-3 file:py-1 file:font-bold file:text-[var(--teal)]"/></label><p className="mt-2 text-xs text-[var(--muted)]">Columns: Date, Description, and Amount; or Date, Description, Debit, and Credit. Deposits are positive and withdrawals are negative.</p><button disabled={busy||!accountId} className="mt-4 rounded-xl bg-[var(--teal)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-45">Import and deduplicate</button></form></div>
    {accountId?<><div className="card mt-4 overflow-hidden"><div className="border-b border-[var(--line)] bg-[var(--canvas)] px-5 py-3"><h3 className="font-extrabold text-[var(--navy)]">Statement review</h3><p className="text-xs text-[var(--muted)]">{rows.length} recent rows · exact amount matches only</p></div>{rows.length?rows.map(row=>{const candidates=data.candidates.filter(candidate=>candidate.bankAccountId===accountId&&candidate.amount===row.amount);return <div key={row.id} className="grid gap-3 border-b border-[var(--line)] p-4 last:border-0 lg:grid-cols-[1fr_120px_minmax(260px,1fr)_auto]"><div><div className="font-bold">{row.description}</div><div className="text-xs text-[var(--muted)]">{row.postedOn} · <span className="capitalize">{row.status}</span>{row.note?` · ${row.note}`:""}</div></div><strong className={row.amount>0?"text-[var(--teal)]":"text-[var(--navy)]"}>{money.format(row.amount)}</strong>{row.status==="unreviewed"?<select aria-label={`Journal match for ${row.description}`} value={selectedMatches[row.id]??""} onChange={event=>setSelectedMatches(current=>({...current,[row.id]:event.target.value}))} className="input mt-0"><option value="">{candidates.length?"Choose posted journal":"No exact journal candidate"}</option>{candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}</select>:<div className="text-xs font-semibold text-[var(--muted)]">{row.status==="matched"?data.candidates.find(x=>x.id===row.matchedId)?.label??"Matched journal":"Excluded from matching"}</div>}<div className="flex gap-2">{row.status==="unreviewed"?<><button aria-label={`Match ${row.description}`} disabled={busy||!selectedMatches[row.id]} onClick={()=>void run(()=>reviewBankTransaction(companyId,row.id,"match",selectedMatches[row.id]),"Statement row matched.")} className="rounded-lg bg-[var(--teal)] px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><Link2 size={14}/></button><button aria-label={`Exclude ${row.description}`} disabled={busy} onClick={()=>{const reason=window.prompt("Why should this row be excluded from matching?");if(reason)void run(()=>reviewBankTransaction(companyId,row.id,"exclude",undefined,reason),"Statement row excluded.")}} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold">Exclude</button></>:<button aria-label={`Undo review for ${row.description}`} disabled={busy||Boolean(row.reconciliationId)} onClick={()=>void run(()=>reviewBankTransaction(companyId,row.id,"unmatch"),"Statement row returned to review.")} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs font-bold disabled:opacity-40">Undo</button>}</div></div>}):<div className="p-8 text-center text-sm text-[var(--muted)]">Import a CSV statement to begin matching.</div>}</div>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><form onSubmit={reconcile} className="card p-5"><h3 className="font-extrabold text-[var(--navy)]">Calculate a statement period</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold">Starts<input required name="startsOn" type="date" defaultValue={today.slice(0,8)+"01"} className="input"/></label><label className="text-xs font-bold">Ends<input required name="endsOn" type="date" defaultValue={today} className="input"/></label><label className="text-xs font-bold">Closing balance<input required name="balance" type="number" step="0.01" className="input" placeholder="0.00"/></label></div><button disabled={busy} className="mt-4 rounded-xl bg-[var(--navy)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-45">Calculate difference</button></form><div className="card p-5"><h3 className="font-extrabold text-[var(--navy)]">Reconciliation history</h3><div className="mt-3 space-y-3">{reconciliations.length?reconciliations.map(item=>{const difference=reconciliationDifference(item);return <div key={item.id} className="rounded-xl border border-[var(--line)] p-3"><div className="flex items-center justify-between gap-2"><strong>{item.startsOn} to {item.endsOn}</strong><span className={`pill ${item.status==="completed"?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{item.status}</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><span>Statement<br/><b>{money.format(item.statementBalance)}</b></span><span>Books<br/><b>{money.format(item.bookBalance)}</b></span><span>Difference<br/><b className={difference?"text-red-700":"text-emerald-700"}>{money.format(difference)}</b></span></div>{item.status==="draft"?<button disabled={busy||difference!==0} onClick={()=>void run(()=>completeBankReconciliation(companyId,item.id),"Reconciliation completed and locked.")} className="mt-3 flex items-center gap-2 rounded-lg bg-[var(--teal)] px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><CheckCircle2 size={14}/>Complete and lock</button>:null}</div>}):<p className="text-sm text-[var(--muted)]">No reconciliations yet.</p>}</div></div></div>
    </>:null}
  </section>
}
function message(cause:unknown){return cause instanceof Error?cause.message:"Unable to update bank reconciliation."}
