"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Mail,Pencil,Search,ShieldCheck,Trash2,X} from "lucide-react";
import {roles,Role} from "@/lib/permissions";
import {canChangeMember,demoMembers,isLastActiveOwner,MemberDraft,MemberStatus,roleLabel,TeamMember,validateMember} from "@/lib/team";
import {inviteTeamMember,listTeamMembers,removeTeamMember,resendTeamInvitation,updateTeamMember} from "@/app/actions/team";
const key="kings-team-v1",blank=():MemberDraft=>({name:"",email:"",role:"driver",status:"Invited"});
export function TeamWorkspace({openCreate,onCreateClosed,companyId}:{openCreate:boolean;onCreateClosed:()=>void;companyId?:string}){
 const [members,setMembers]=useState<TeamMember[]>(companyId?[]:demoMembers),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(""),[editing,setEditing]=useState<TeamMember|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{if(companyId){listTeamMembers(companyId).then(setMembers).catch(cause=>setNotice(cause instanceof Error?cause.message:"Unable to load team.")).finally(()=>setLoaded(true));return}try{const saved=localStorage.getItem(key);if(saved)setMembers(JSON.parse(saved) as TeamMember[])}catch{}setLoaded(true)},[companyId]);useEffect(()=>{if(loaded&&!companyId)localStorage.setItem(key,JSON.stringify(members))},[loaded,members,companyId]);const visible=useMemo(()=>{const q=query.trim().toLowerCase();return members.filter(x=>!q||`${x.name} ${x.email} ${x.role} ${x.status}`.toLowerCase().includes(q))},[members,query]);
 async function save(draft:MemberDraft,id?:string){const current=id?members.find(x=>x.id===id):null;if(current&&!canChangeMember(current,draft,members)){setNotice("Assign another active owner before changing this account.");return}try{const saved=companyId?(id?await updateTeamMember(companyId,draft,id):await inviteTeamMember(companyId,draft,members)):{...draft,id:id??crypto.randomUUID(),invitedAt:new Date().toISOString(),lastActive:""};setMembers(all=>id?all.map(x=>x.id===id?{...x,...saved}:x):[saved,...all]);setEditing(null);setNotice(id?"Team member updated.":`Invitation sent to ${draft.email}.`);onCreateClosed()}catch(cause){setNotice(cause instanceof Error?cause.message:"Unable to save team member.")}}
 async function remove(member:TeamMember){if(isLastActiveOwner(member,members)){setNotice("The last active owner cannot be removed.");return}if(confirm(`Remove ${member.name} from the team?`))try{if(companyId)await removeTeamMember(companyId,member.id);setMembers(x=>x.filter(y=>y.id!==member.id))}catch(cause){setNotice(cause instanceof Error?cause.message:"Unable to remove team member.")}}
 async function resend(member:TeamMember){try{if(companyId)await resendTeamInvitation(companyId,member.id);setNotice(companyId?`Invitation resent to ${member.email}.`:`Demo invitation prepared for ${member.email}.`)}catch(cause){setNotice(cause instanceof Error?cause.message:"Unable to resend invitation.")}}
 return <>{notice&&<div className="mb-4 flex justify-between rounded-xl border border-[var(--line)] bg-white p-3 text-sm"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={16}/></button></div>}<div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-white py-2.5 pl-10" placeholder="Search name, email, role, or status…"/></div><div className="card mt-4 overflow-hidden">{visible.map(member=><div className="flex items-center gap-3 border-b border-[var(--line)] p-4 last:border-0 md:px-6" key={member.id}><div className="grid size-10 shrink-0 place-items-center rounded-full bg-[var(--navy)] text-xs font-extrabold text-white">{member.name.split(/\s+/).map(x=>x[0]).slice(0,2).join("")}</div><div className="min-w-0 flex-1"><b>{member.name}</b><p className="truncate text-xs text-[var(--muted)]">{member.email}</p></div><span className="pill hidden bg-[var(--teal-light)] text-[var(--teal)] sm:inline-flex"><ShieldCheck size={13}/>{roleLabel(member.role)}</span><span className={`pill ${member.status==="Active"?"bg-[#e8f5ee] text-[#287250]":member.status==="Suspended"?"bg-red-50 text-red-700":"bg-[#fff8e4] text-[#9a6c1d]"}`}>{member.status}</span>{member.status==="Invited"&&<button onClick={()=>void resend(member)} title="Resend invitation" className="p-2 text-[var(--teal)]"><Mail size={16}/></button>}<button onClick={()=>setEditing(member)} title="Edit" className="p-2 text-[var(--muted)]"><Pencil size={16}/></button><button onClick={()=>remove(member)} title="Remove" className="p-2 text-[var(--muted)] hover:text-red-600"><Trash2 size={16}/></button></div>)}{!visible.length&&<p className="p-10 text-center text-sm text-[var(--muted)]">No team members match this search.</p>}</div>{(openCreate||editing)&&<MemberForm member={editing} members={members} onClose={()=>{setEditing(null);onCreateClosed()}} onSave={save}/>}</>;
}
function MemberForm({member,members,onClose,onSave}:{member:TeamMember|null;members:TeamMember[];onClose:()=>void;onSave:(x:MemberDraft,id?:string)=>void}){const [draft,setDraft]=useState<MemberDraft>(member?{name:member.name,email:member.email,role:member.role,status:member.status}:blank),[errors,setErrors]=useState<Record<string,string>>({});const patch=(x:Partial<MemberDraft>)=>setDraft(v=>({...v,...x}));function submit(e:FormEvent){e.preventDefault();const found=validateMember(draft,members,member?.id);if(member&&!canChangeMember(member,draft,members))found.owner="Assign another active owner before changing this account.";setErrors(found);if(!Object.keys(found).length)onSave(draft,member?.id)}return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} className="w-full rounded-t-3xl bg-white p-6 sm:max-w-lg sm:rounded-3xl"><div className="flex justify-between"><h2 className="display text-2xl font-extrabold">{member?"Edit team member":"Invite person"}</h2><button type="button" aria-label="Close team member form" onClick={onClose}><X/></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-bold">Full name<input value={draft.name} onChange={e=>patch({name:e.target.value})} className="input"/></label><label className="block text-xs font-bold">Email<input type="email" value={draft.email} onChange={e=>patch({email:e.target.value})} className="input"/></label><label className="block text-xs font-bold">Role<select value={draft.role} onChange={e=>patch({role:e.target.value as Role})} className="input">{roles.map(role=><option value={role} key={role}>{roleLabel(role)}</option>)}</select></label><label className="block text-xs font-bold">Status<select value={draft.status} onChange={e=>patch({status:e.target.value as MemberStatus})} className="input"><option>Invited</option><option>Active</option><option>Suspended</option></select></label>{Object.values(errors).map(x=><p key={x} className="text-sm text-red-600">{x}</p>)}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-3">Cancel</button><button className="rounded-xl bg-[var(--teal)] px-5 py-3 font-bold text-white">{member?"Save changes":"Send invitation"}</button></div></form></div>}
