import {test,expect,type Page} from "@playwright/test";
import {createClient} from "@supabase/supabase-js";
import {readFileSync} from "node:fs";
const local=JSON.parse(readFileSync(process.env.KINGS_TEST_CONFIG!,"utf8"));
const admin=createClient(local.API_URL,local.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const password="Local-test-only-48!";
async function user(name:string){const email=`${name}-${crypto.randomUUID()}@test.local`;const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name}});if(error)throw error;return{id:data.user!.id,email}}
async function insert(table:string,values:Record<string,unknown>){const{data,error}=await admin.from(table).insert(values).select().single();if(error)throw error;return data}
async function login(page:Page,email:string){await page.goto("/login");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Sign in",exact:true}).click()}
async function receiptPhoto(page:Page){const base64=await page.evaluate(()=>{const canvas=document.createElement("canvas");canvas.width=1100;canvas.height=1100;const context=canvas.getContext("2d")!;context.fillStyle="white";context.fillRect(0,0,1100,1100);context.fillStyle="black";context.font="36px monospace";["PILOT TRAVEL CENTER","123 MAIN STREET","09/09/2026 12:34","GALLONS 25.500","PRICE/GAL $3.899","SUBTOTAL $99.42","TAX $1.58","TOTAL $101.00","CASH $120.00","CHANGE $19.00"].forEach((line,i)=>context.fillText(line,60,90+i*85));return canvas.toDataURL("image/png").split(",")[1]});return{name:"scanned-fuel.png",mimeType:"image/png",buffer:Buffer.from(base64,"base64")}}

test("real browser OCR requires review and saves an office fuel entry with its photo",async({page})=>{
 const owner=await user("OcrOwner"),company=await insert("companies",{legal_name:"OCR Test",display_name:"OCR Test",created_by:owner.id});await insert("company_memberships",{company_id:company.id,user_id:owner.id,role:"owner"});await insert("trucks",{company_id:company.id,unit_number:"OCR-1"});
 const errors:string[]=[],external:string[]=[];page.on("pageerror",error=>errors.push(error.message));page.on("request",request=>{if(request.url().startsWith("http")&&!["localhost","127.0.0.1"].includes(new URL(request.url()).hostname))external.push(request.url())});
 await login(page,owner.email);await expect(page).toHaveURL(/\/workspace/);await page.getByRole("navigation",{name:"Primary navigation"}).getByRole("button",{name:"Fuel & mileage",exact:true}).click();await page.getByRole("button",{name:"Record fuel",exact:true}).click();
 const scanner=page.getByRole("region",{name:"Receipt auto-fill"});await scanner.getByLabel("Choose receipt photo for auto-fill").setInputFiles(await receiptPhoto(page));
 await expect(scanner.getByLabel("Suggested vendor",{exact:true})).toHaveValue("PILOT TRAVEL CENTER",{timeout:90000});await expect(scanner.getByLabel("Suggested total (USD)")).toHaveValue("101.00");await expect(scanner.getByLabel("Suggested gallons")).toHaveValue("25.5");await expect(page.getByLabel("Vendor",{exact:true})).toHaveValue("");
 await scanner.getByRole("button",{name:"Apply suggestions",exact:true}).click();await expect(page.getByLabel("Date",{exact:true})).toHaveValue("2026-09-09");await expect(page.getByLabel("Total cost",{exact:true})).toHaveValue("101");await page.getByLabel("Unit number",{exact:true}).fill("OCR-1");await page.getByLabel("Odometer",{exact:true}).fill("1000");await page.getByRole("button",{name:"Save fuel entry",exact:true}).click();await expect(page.getByRole("link",{name:"scanned-fuel.png"})).toBeVisible();
 const {data:entries,error}=await admin.from("fuel_entries").select("id,total_cost,gallons,receipts(id)").eq("company_id",company.id);expect(error).toBeNull();expect(entries).toHaveLength(1);expect(Number(entries![0].total_cost)).toBe(101);expect(Number(entries![0].gallons)).toBe(25.5);expect(entries![0].receipts).toHaveLength(1);expect(errors).toEqual([]);expect(external).toEqual([]);
 await page.screenshot({path:test.info().outputPath("office-ocr.png"),fullPage:true});
});

test("driver reviews OCR fields, then explicitly chooses the submitted fuel entry for its photo",async({page})=>{
 const driverUser=await user("OcrDriver"),company=await insert("companies",{legal_name:"Driver OCR Test",display_name:"Driver OCR Test",created_by:driverUser.id});await insert("company_memberships",{company_id:company.id,user_id:driverUser.id,role:"driver"});const driver=await insert("drivers",{company_id:company.id,profile_id:driverUser.id});const truck=await insert("trucks",{company_id:company.id,unit_number:"OCR-D"});await insert("loads",{company_id:company.id,load_number:"OCR-LOAD",driver_id:driver.id,truck_id:truck.id,status:"dispatched"});
 await page.setViewportSize({width:390,height:844});await login(page,driverUser.email);await expect(page).toHaveURL(/\/driver/);await page.getByRole("button",{name:"Fuel",exact:true}).click();const scanner=page.getByRole("region",{name:"Receipt auto-fill"});await scanner.getByLabel("Take receipt photo for auto-fill").setInputFiles(await receiptPhoto(page));await expect(scanner.getByLabel("Suggested vendor",{exact:true})).toHaveValue("PILOT TRAVEL CENTER",{timeout:90000});await scanner.getByRole("button",{name:"Apply suggestions",exact:true}).click();await page.getByLabel("Odometer",{exact:true}).fill("1100");await page.getByRole("button",{name:"Submit fuel entry",exact:true}).click();const select=page.getByRole("combobox",{name:"Fuel entry",exact:true});await expect(select).toHaveValue("");await expect(select).toContainText("PILOT TRAVEL CENTER");const options=await select.locator("option").evaluateAll(nodes=>nodes.map(option=>(option as HTMLOptionElement).value).filter(Boolean));await select.selectOption(options[0]);await page.getByRole("button",{name:"Attach scanned photo to this entry",exact:true}).click();await expect(page.getByRole("link",{name:"scanned-fuel.png"})).toBeVisible();await expect(page.getByText("Photo waiting to attach:",{exact:false})).toHaveCount(0);
 const {data:entries}=await admin.from("fuel_entries").select("total_cost,receipts(id)").eq("company_id",company.id);expect(entries).toHaveLength(1);expect(Number(entries![0].total_cost)).toBe(101);expect(entries![0].receipts).toHaveLength(1);
 await page.screenshot({path:test.info().outputPath("driver-ocr.png"),fullPage:true});
});
