"use client";
import Image from "next/image";
import {useEffect,useState,type ChangeEvent} from "react";
import {loadInvoiceTemplate,previewInvoiceTemplate,saveInvoiceTemplate} from "@/app/actions/invoice-template";
import {defaultInvoiceTemplate,parseInvoiceTemplate,type InvoiceTemplate} from "@/lib/invoice-template";
const message=(cause:unknown)=>cause instanceof Error?cause.message:"Unable to update the invoice template.";
export function InvoiceTemplateEditor({companyId,onBack}:{companyId:string;onBack:()=>void}){
 const [draft,setDraft]=useState<InvoiceTemplate>(defaultInvoiceTemplate),[saved,setSaved]=useState<InvoiceTemplate|null>(null),[canEdit,setCanEdit]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 const dirty=!!saved&&JSON.stringify(draft)!==JSON.stringify(saved);
 useEffect(()=>{let active=true;loadInvoiceTemplate(companyId).then(value=>{if(active){setDraft(value.template);setSaved(value.template);setCanEdit(value.canEdit);setError("")}}).catch(cause=>{if(active)setError(message(cause))});return()=>{active=false}},[companyId,reload]);
 function patch(value:Partial<InvoiceTemplate>){setDraft(current=>({...current,...value}));setNotice("")}
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(!["image/png","image/jpeg"].includes(file.type)||file.size>300000){setError("Choose a PNG or JPEG logo up to 300 KB.");return}setBusy(true);setError("");try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Unable to read logo."));reader.readAsDataURL(file)});patch({logoDataUrl:data})}catch(cause){setError(message(cause))}finally{setBusy(false)}}
 async function save(){if(busy||!canEdit)return;setBusy(true);setError("");setNotice("");try{const value=await saveInvoiceTemplate(companyId,parseInvoiceTemplate(draft));setDraft(value);setSaved(value);setNotice("Invoice template saved. PDF downloads and new invoice emails now use this design.")}catch(cause){setError(message(cause))}finally{setBusy(false)}}
 async function preview(){if(busy)return;setBusy(true);setError("");try{const data=await previewInvoiceTemplate(companyId,parseInvoiceTemplate(draft)),bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:"application/pdf"}));const link=document.createElement("a");link.href=url;link.download="invoice-template-preview.pdf";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(cause){setError(message(cause))}finally{setBusy(false)}}
 function back(){if(!dirty||confirm("Leave without saving your template changes?"))onBack()}
 const field=(key:Exclude<keyof InvoiceTemplate,"layout"|"accentColor"|"logoDataUrl">,label:string,maxLength:number,multiline=false)=><label className="block text-sm font-bold" key={key}>{label}{multiline?<textarea className="input min-h-24" maxLength={maxLength} value={draft[key]} onChange={event=>patch({[key]:event.target.value})}/>:<input className="input" type={key==="email"?"email":"text"} maxLength={maxLength} value={draft[key]} onChange={event=>patch({[key]:event.target.value})}/>}</label>;
 return <section aria-label="Invoice template editor">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><button type="button" disabled={busy} onClick={back} className="text-sm font-bold text-[var(--teal)]">← Back to invoices</button><h2 className="display mt-3 text-2xl font-extrabold">Invoice template</h2><p className="mt-1 max-w-2xl text-sm text-[var(--muted)]">Make your invoices look like your business. Saved changes apply to future PDF downloads and new emails. Previously emailed copies stay unchanged.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={!saved||busy} onClick={()=>void preview()} className="rounded-xl border px-4 py-3 font-bold disabled:opacity-50">Preview PDF</button><button type="button" disabled={!dirty||!canEdit||busy} onClick={()=>void save()} className="rounded-xl bg-[var(--teal)] px-4 py-3 font-bold text-white disabled:opacity-50">{busy?"Working…":"Save template"}</button></div></div>
  {error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}{!saved&&<button type="button" className="ml-3 underline" onClick={()=>setReload(x=>x+1)}>Retry</button>}</p>}{notice&&<p role="status" className="mb-4 rounded-xl bg-[var(--teal-light)] p-3 text-sm">{notice}</p>}
  {!saved?<p role="status">{error?"Template unavailable.":"Loading invoice template…"}</p>:<div className="grid items-start gap-6 xl:grid-cols-[minmax(300px,1fr)_minmax(0,1.1fr)]">
   <fieldset disabled={!canEdit||busy} className="min-w-0 space-y-5 disabled:opacity-75">
    {!canEdit&&<p className="text-sm">You have read-only access. Ask an owner, administrator or accountant to edit this template.</p>}
    <div className="card space-y-4 p-5"><h3 className="font-extrabold">Business information</h3>{field("businessName","Business name on invoices",150)}{field("address","Business address",500,true)}<div className="grid gap-4 sm:grid-cols-2">{field("phone","Phone number",60)}{field("email","Contact email",254)}</div>{field("website","Website",150)}{field("taxId","Tax / registration number (optional)",100)}<p className="text-xs text-[var(--muted)]">Contact information appears on the PDF. This does not change your legal company settings or connect an email sender.</p></div>
    <div className="card space-y-4 p-5"><h3 className="font-extrabold">Logo and design</h3><label className="block text-sm font-bold">Business logo<input type="file" accept="image/png,image/jpeg" onChange={event=>void upload(event)} className="mt-2 block w-full min-w-0 text-sm"/></label><p className="text-xs text-[var(--muted)]">PNG or JPEG, up to 300 KB and 4096 × 4096 pixels.</p>{draft.logoDataUrl&&<div className="flex items-center gap-4"><Image unoptimized src={draft.logoDataUrl} alt="Business logo" width={140} height={70} className="h-16 w-32 object-contain"/><button type="button" className="rounded-lg border px-3 py-2 text-sm" onClick={()=>patch({logoDataUrl:""})}>Remove logo</button></div>}
     <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Accent color<div className="mt-2 flex items-center gap-3"><input aria-label="Accent color" type="color" value={draft.accentColor} onChange={event=>patch({accentColor:event.target.value})} className="h-10 w-14 cursor-pointer rounded border"/><span className="font-mono text-xs">{draft.accentColor}</span></div></label><label className="text-sm font-bold">Layout<select className="input" value={draft.layout} onChange={event=>patch({layout:event.target.value as InvoiceTemplate["layout"]})}><option value="modern">Modern — color band</option><option value="classic">Classic — clean letterhead</option></select></label></div>
    </div><div className="card space-y-4 p-5"><h3 className="font-extrabold">Payment and footer</h3>{field("paymentInstructions","Payment instructions",1500,true)}{field("footer","Footer message",500,true)}<p className="text-xs text-[var(--muted)]">Include how customers should pay or a thank-you message. Invoice amounts and due dates come from each invoice.</p></div>
   </fieldset>
   <div className="min-w-0 xl:sticky xl:top-5"><div className="mb-3 flex justify-between text-xs font-bold text-[var(--muted)]"><span>DESIGN PREVIEW</span><span>{dirty?"Unsaved changes":"Saved template"}</span></div><div className="overflow-hidden rounded-xl border bg-white shadow-sm">
    {draft.layout==="modern"&&<div className="h-3" style={{backgroundColor:draft.accentColor}}/>}
    <div className="space-y-5 p-5 sm:p-8" style={{overflowWrap:"anywhere"}}><div className="flex justify-between gap-4 text-sm font-bold" style={{color:draft.accentColor}}><span>INV-PREVIEW</span><span>INVOICE</span></div>
     {draft.logoDataUrl&&<Image unoptimized src={draft.logoDataUrl} alt="Logo on preview invoice" width={140} height={70} className="h-16 w-36 object-contain object-left"/>}
     <div><h3 className="text-xl font-extrabold">{draft.businessName||"Your business"}</h3>{[draft.address,draft.phone,draft.email,draft.website,draft.taxId?`Tax / registration: ${draft.taxId}`:""].filter(Boolean).map((line,index)=><p key={index} className="mt-1 whitespace-pre-wrap text-sm text-[var(--muted)]">{line}</p>)}</div>
     <div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs font-bold" style={{color:draft.accentColor}}>BILL TO</p><p className="mt-2 font-bold">Sample customer</p><p>123 Customer Street<br/>Atlanta, GA 30301</p></div><div className="text-right"><p>Invoice date: Today</p><p>Due: In 30 days</p><p className="mt-1 text-xs">Amounts in USD</p></div></div>
     <div className="border-y py-3 text-sm"><div className="flex justify-between gap-3 font-bold" style={{color:draft.accentColor}}><span>Description</span><span>Amount</span></div><div className="mt-3 flex justify-between gap-3"><span>Freight transportation services<br/><span className="text-xs text-[var(--muted)]">1 × $1,250.00</span></span><span>$1,250.00</span></div></div><div className="ml-auto max-w-60 space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><span>$1,250.00</span></p><p className="flex justify-between"><span>Tax</span><span>$0.00</span></p><p className="flex justify-between font-extrabold"><span>Balance due</span><span>$1,250.00</span></p></div>
     {draft.paymentInstructions&&<div><p className="text-xs font-bold" style={{color:draft.accentColor}}>PAYMENT INSTRUCTIONS</p><p className="mt-2 whitespace-pre-wrap text-sm">{draft.paymentInstructions}</p></div>}{draft.footer&&<p className="whitespace-pre-wrap text-sm text-[var(--muted)]">{draft.footer}</p>}
    </div></div><p className="mt-3 text-xs text-[var(--muted)]">Sample content. Choose Preview PDF to check exact pagination, logo, and document formatting before saving.</p></div>
  </div>}
 </section>;
}
