"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {CircleDollarSign,Pencil,Search,Trash2,X} from "lucide-react";
import {deleteVendorBill,listVendorBills,recordVendorBillPayment,saveVendorBill} from "@/app/actions/payables";
import {billOutstanding,demoVendorBills,filterVendorBills,VendorBill,VendorBillDraft,VendorBillPaymentDraft,vendorBillStatuses,validateVendorBill,validateVendorBillPayment} from "@/lib/payables";

const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const today=()=>new Date().toISOString().slice(0,10);
const blank=():VendorBillDraft=>({vendor:"",billNumber:"",issuedOn:today(),dueOn:"",status:"Open",amount:0,description:""});

export function PayablesWorkspace({openCreate,onCreateClosed,companyId,readOnly=false}:{openCreate:boolean;onCreateClosed:()=>void;companyId?:string;readOnly?:boolean}){
 const [records,setRecords]=useState<VendorBill[]>(companyId?[]:demoVendorBills),[editing,setEditing]=useState<VendorBill|null>(null),[paying,setPaying]=useState<VendorBill|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState("All statuses"),[error,setError]=useState(""),[busy,setBusy]=useState(Boolean(companyId));
 useEffect(()=>{let active=true;if(!companyId)return;setBusy(true);setError("");listVendorBills(companyId).then(data=>{if(active)setRecords(data)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load vendor bills.")}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[companyId]);
 const visible=useMemo(()=>filterVendorBills(records,query,status),[records,query,status]);
 const outstanding=records.reduce((total,bill)=>total+billOutstanding(bill),0);
 async function save(draft:VendorBillDraft,id?:string){setError("");setBusy(true);try{const saved=companyId?await saveVendorBill(companyId,draft,id):{...draft,id:id??crypto.randomUUID(),payments:id?records.find(x=>x.id===id)?.payments??[]:[],status:draft.status};setRecords(current=>id?current.map(item=>item.id===id?saved:item):[saved,...current]);setEditing(null);onCreateClosed()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save vendor bill.")}finally{setBusy(false)}}
 async function pay(bill:VendorBill,draft:VendorBillPaymentDraft){setError("");setBusy(true);try{let saved:VendorBill;if(companyId)saved=await recordVendorBillPayment(companyId,bill.id,draft);else{const payments=[...bill.payments,{...draft,id:crypto.randomUUID()}],remaining=Math.max(0,bill.amount-payments.reduce((sum,item)=>sum+item.amount,0));saved={...bill,payments,status:remaining===0?"Paid":"Open"}}setRecords(current=>current.map(item=>item.id===bill.id?saved:item));setPaying(null)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to record payment.")}finally{setBusy(false)}}
 async function remove(bill:VendorBill){if(!confirm("Delete bill "+bill.billNumber+"?"))return;setError("");setBusy(true);try{if(companyId)await deleteVendorBill(companyId,bill.id);setRecords(current=>current.filter(item=>item.id!==bill.id))}catch(cause){setError(cause instanceof Error?cause.message:"Unable to delete vendor bill.")}finally{setBusy(false)}}
 return <>
  {error&&<p role="alert" className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  {busy&&<p role="status" className="mb-3 text-xs font-bold text-[var(--teal)]">Syncing payables…</p>}
  <div className="grid gap-3 sm:grid-cols-3"><div className="card p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Outstanding</p><strong className="display mt-1 block text-2xl">{currency.format(outstanding)}</strong></div><div className="card p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Open bills</p><strong className="display mt-1 block text-2xl">{records.filter(x=>x.status==="Open").length}</strong></div><div className="card p-4"><p className="text-xs font-bold uppercase text-[var(--muted)]">Past due</p><strong className="display mt-1 block text-2xl">{records.filter(x=>x.status==="Open"&&x.dueOn<today()).length}</strong></div></div>
  <div className="mt-4 flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17}/><input aria-label="Search vendor bills" value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-xl border border-[var(--line)] py-2.5 pl-10 pr-3 text-sm" placeholder="Search vendor or bill number…"/></div><select aria-label="Filter vendor bills by status" value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border border-[var(--line)] bg-white px-3 text-sm font-bold"><option>All statuses</option>{vendorBillStatuses.map(value=><option key={value}>{value}</option>)}</select></div>
  <div className="card mt-3 overflow-hidden"><div className="grid grid-cols-[1fr_auto] gap-3 border-b border-[var(--line)] bg-[var(--canvas)] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[var(--muted)]"><span>Vendor bill</span><span>Outstanding</span></div>{visible.length?visible.map(bill=>{const remaining=billOutstanding(bill);return <div className="flex items-center gap-4 border-b border-[var(--line)] p-4 last:border-0 md:px-5" key={bill.id}><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--teal-light)] text-[var(--teal)]"><CircleDollarSign size={18}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{bill.vendor}</div><div className="truncate text-xs text-[var(--muted)]">{bill.billNumber} · due {bill.dueOn} · {bill.description||"No description"}</div></div><span className={"pill "+(bill.status==="Paid"?"bg-[#e8f5ee] text-[#287250]":bill.status==="Void"?"bg-slate-100 text-slate-500":"bg-orange-50 text-orange-700")}>{bill.status}</span><strong className="min-w-24 text-right">{currency.format(remaining)}</strong>{!readOnly&&<div className="flex">{bill.status==="Open"&&remaining>0&&<button aria-label={"Pay "+bill.billNumber} onClick={()=>setPaying(bill)} className="rounded-lg px-2 py-1 text-xs font-bold text-[var(--teal)]">Pay</button>}{!["Paid","Void"].includes(bill.status)&&bill.payments.length===0&&<button aria-label={"Edit "+bill.billNumber} onClick={()=>setEditing(bill)} className="rounded-lg p-2 text-[var(--muted)]"><Pencil size={16}/></button>}{bill.status==="Draft"&&bill.payments.length===0&&<button aria-label={"Delete "+bill.billNumber} onClick={()=>void remove(bill)} className="rounded-lg p-2 text-[var(--muted)]"><Trash2 size={16}/></button>}</div>}</div>}):<p className="p-10 text-center text-sm text-[var(--muted)]">No vendor bills match this view.</p>}</div>
  {(openCreate||editing)&&!readOnly&&<BillForm bill={editing} onCancel={()=>{setEditing(null);onCreateClosed()}} onSave={save}/>}
  {paying&&!readOnly&&<PaymentForm bill={paying} onCancel={()=>setPaying(null)} onSave={draft=>pay(paying,draft)}/>}
 </>;
}

function BillForm({bill,onCancel,onSave}:{bill:VendorBill|null;onCancel:()=>void;onSave:(draft:VendorBillDraft,id?:string)=>void}){
 const [draft,setDraft]=useState<VendorBillDraft>(bill?{vendor:bill.vendor,billNumber:bill.billNumber,issuedOn:bill.issuedOn,dueOn:bill.dueOn,status:bill.status,amount:bill.amount,description:bill.description}:blank()),[errors,setErrors]=useState<Record<string,string>>({});
 function patch(value:Partial<VendorBillDraft>){setDraft(current=>({...current,...value}))}
 function submit(event:FormEvent){event.preventDefault();const next=validateVendorBill(draft);setErrors(next);if(!Object.keys(next).length)onSave(draft,bill?.id)}
 return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onCancel}><form onSubmit={submit} onMouseDown={event=>event.stopPropagation()} className="max-h-[95vh] w-full overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-xl sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-bold text-[var(--teal)]">Accounts payable</p><h2 className="display text-2xl font-extrabold">{bill?"Edit vendor bill":"Add vendor bill"}</h2></div><button type="button" aria-label="Close" onClick={onCancel}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Vendor" error={errors.vendor} wide><input value={draft.vendor} onChange={e=>patch({vendor:e.target.value})} className="input"/></Field><Field label="Bill number" error={errors.billNumber}><input value={draft.billNumber} onChange={e=>patch({billNumber:e.target.value})} className="input"/></Field><Field label="Amount" error={errors.amount}><input type="number" min="0.01" step="0.01" value={draft.amount||""} onChange={e=>patch({amount:Number(e.target.value)})} className="input"/></Field><Field label="Issue date" error={errors.issuedOn}><input type="date" value={draft.issuedOn} onChange={e=>patch({issuedOn:e.target.value})} className="input"/></Field><Field label="Due date" error={errors.dueOn}><input type="date" value={draft.dueOn} onChange={e=>patch({dueOn:e.target.value})} className="input"/></Field><Field label="Status"><select value={draft.status} onChange={e=>patch({status:e.target.value as VendorBillDraft["status"]})} className="input">{vendorBillStatuses.map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Description" wide><input value={draft.description} onChange={e=>patch({description:e.target.value})} className="input"/></Field></div>{draft.status==="Paid"&&<p className="mt-3 text-sm text-[var(--muted)]">Saving as paid records the full balance as paid today. Paid bills require an adjustment for later corrections.</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl border px-4 py-3 text-sm font-bold">Cancel</button><button className="rounded-xl bg-[var(--teal)] px-5 py-3 text-sm font-bold text-white">Save bill</button></div></form></div>
}

function PaymentForm({bill,onCancel,onSave}:{bill:VendorBill;onCancel:()=>void;onSave:(draft:VendorBillPaymentDraft)=>void}){
 const remaining=billOutstanding(bill),[draft,setDraft]=useState<VendorBillPaymentDraft>({paidOn:today(),amount:remaining,reference:""}),[errors,setErrors]=useState<Record<string,string>>({});
 function submit(event:FormEvent){event.preventDefault();const next=validateVendorBillPayment(draft,remaining);setErrors(next);if(!Object.keys(next).length)onSave(draft)}
 return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onCancel}><form onSubmit={submit} onMouseDown={event=>event.stopPropagation()} className="w-full rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-md sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-bold text-[var(--teal)]">{bill.vendor} · {bill.billNumber}</p><h2 className="display text-2xl font-extrabold">Record payment</h2><p className="mt-1 text-sm text-[var(--muted)]">Outstanding {currency.format(remaining)}</p></div><button type="button" aria-label="Close" onClick={onCancel}><X/></button></div><div className="mt-5 grid gap-4"><Field label="Payment date" error={errors.paidOn}><input type="date" value={draft.paidOn} onChange={e=>setDraft({...draft,paidOn:e.target.value})} className="input"/></Field><Field label="Amount" error={errors.amount}><input type="number" min="0.01" max={remaining} step="0.01" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})} className="input"/></Field><Field label="Reference"><input value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} className="input" placeholder="ACH, check, or card reference"/></Field></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl border px-4 py-3 text-sm font-bold">Cancel</button><button className="rounded-xl bg-[var(--teal)] px-5 py-3 text-sm font-bold text-white">Record payment</button></div></form></div>
}

function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:React.ReactNode}){return <label className={"text-xs font-bold "+(wide?"sm:col-span-2":"")}>{label}{children}{error&&<span className="mt-1 block text-red-600">{error}</span>}</label>}
