"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Check,ChevronRight,ClipboardCheck,Search,X,XCircle} from "lucide-react";
import {approvalSummary,ApprovalItem,decideApproval,demoApprovals} from "@/lib/approvals";
import {listApprovals,reviewApproval} from "@/app/actions/approvals";
const key="kings-approvals-v1",money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
export function ApprovalsWorkspace({openNext,onOpenHandled,companyId}:{openNext:boolean;onOpenHandled:()=>void;companyId?:string}){
 const [items,setItems]=useState<ApprovalItem[]>(companyId?[]:demoApprovals),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("Pending"),[selected,setSelected]=useState<ApprovalItem|null>(null),[error,setError]=useState("");
 useEffect(()=>{if(companyId){listApprovals(companyId).then(setItems).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load approvals.")).finally(()=>setLoaded(true));return}try{const saved=localStorage.getItem(key);if(saved)setItems(JSON.parse(saved) as ApprovalItem[])}catch{}setLoaded(true)},[companyId]);useEffect(()=>{if(loaded&&!companyId)localStorage.setItem(key,JSON.stringify(items))},[loaded,items,companyId]);useEffect(()=>{if(openNext){setSelected(items.find(x=>x.status==="Pending")??null);onOpenHandled()}},[openNext,items,onOpenHandled]);
 const summary=useMemo(()=>approvalSummary(items),[items]),visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(x=>(filter==="All"||x.status===filter)&&(!q||`${x.reference} ${x.submittedBy} ${x.description} ${x.type}`.toLowerCase().includes(q))).sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt))},[items,filter,query]);
 async function reviewed(updated:ApprovalItem){try{setError("");const saved=companyId?await reviewApproval(companyId,updated,updated.status as "Approved"|"Rejected",updated.note):updated;setItems(current=>current.map(x=>x.id===saved.id?saved:x));setSelected(null)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to review approval.")}}
 return <>{error&&<div role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Pending",summary.pending],["Flagged",summary.flagged],["Approved",summary.approved],["Rejected",summary.rejected]].map(([label,value])=><div className="card p-4" key={label}><div className="flex justify-between"><span className="text-xs font-bold text-[var(--muted)]">{label}</span><ClipboardCheck size={17} className="text-[var(--teal)]"/></div><p className="display mt-2 text-2xl font-extrabold">{value}</p></div>)}</div><div className="mt-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border border-[var(--line)] bg-white py-2.5 pl-10" placeholder="Search reference, submitter, or description…"/></div><select aria-label="Filter approvals" value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-[var(--line)] bg-white px-3"><option>All</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></div><div className="card mt-4 overflow-hidden">{visible.map(item=><button onClick={()=>setSelected(item)} key={item.id} className="flex w-full items-center gap-4 border-b border-[var(--line)] p-4 text-left last:border-0 hover:bg-[var(--canvas)] md:px-6"><div className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.flags.length?"bg-[#fff0e8] text-[#c96535]":"bg-[var(--teal-light)] text-[var(--teal)]"}`}>{item.flags.length?<AlertTriangle size={18}/>:<ClipboardCheck size={18}/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate">{item.reference} · {item.type}</b>{item.flags.map(flag=><span key={flag} className="pill hidden bg-[#fff0e8] text-[#c96535] sm:inline-flex">{flag}</span>)}</div><p className="truncate text-xs text-[var(--muted)]">{item.description} · Submitted by {item.submittedBy}</p></div>{item.amount>0&&<b>{money.format(item.amount)}</b>}<span className={`pill ${item.status==="Approved"?"bg-[#e8f5ee] text-[#287250]":item.status==="Rejected"?"bg-red-50 text-red-700":"bg-[#fff8e4] text-[#9a6c1d]"}`}>{item.status}</span><ChevronRight size={17} className="text-[var(--muted)]"/></button>)}{!visible.length&&<p className="p-10 text-center text-sm text-[var(--muted)]">No approval items match this view.</p>}</div>{selected&&<Review item={selected} onClose={()=>setSelected(null)} onReviewed={reviewed}/>}</>;
}
function Review({item,onClose,onReviewed}:{item:ApprovalItem;onClose:()=>void;onReviewed:(x:ApprovalItem)=>void}){const [note,setNote]=useState(item.note),[error,setError]=useState("");function decide(status:"Approved"|"Rejected"){try{onReviewed(decideApproval(item,status,"Kendra Williams",note))}catch(cause){setError(cause instanceof Error?cause.message:"Unable to review item.")}}return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/40 sm:place-items-center" onMouseDown={onClose}><section onMouseDown={e=>e.stopPropagation()} className="w-full rounded-t-3xl bg-white p-6 sm:max-w-xl sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-bold text-[var(--teal)]">{item.type}</p><h2 className="display text-2xl font-extrabold">{item.reference}</h2></div><button onClick={onClose}><X/></button></div><div className="mt-5 rounded-2xl bg-[var(--canvas)] p-5"><p className="font-bold">{item.description}</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><span><small className="block text-[var(--muted)]">Submitted by</small>{item.submittedBy}</span><span><small className="block text-[var(--muted)]">Amount</small>{item.amount?money.format(item.amount):"Not applicable"}</span></div>{item.flags.map(flag=><p key={flag} className="mt-3 flex gap-2 text-sm font-bold text-[#c96535]"><AlertTriangle size={17}/>{flag}</p>)}</div>{item.status==="Pending"?<><label className="mt-4 block text-xs font-bold">Reviewer note<textarea value={note} onChange={e=>setNote(e.target.value)} className="input min-h-24" placeholder="Required when rejecting; optional when approving"/></label>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>decide("Rejected")} className="flex items-center gap-2 rounded-xl border border-red-200 px-4 py-3 font-bold text-red-700"><XCircle size={17}/>Reject</button><button onClick={()=>decide("Approved")} className="flex items-center gap-2 rounded-xl bg-[var(--teal)] px-5 py-3 font-bold text-white"><Check size={17}/>Approve</button></div></>:<div className="mt-4 rounded-xl border p-4 text-sm"><b>{item.status} by {item.reviewedBy}</b><p className="text-[var(--muted)]">{item.note||"No reviewer note."}</p></div>}</section></div>}
