create or replace function public.save_work_order(target_company_id uuid,target_order_id uuid,reference_value text,target_unit_number text,service_type_value text,description_value text,vendor_name text,scheduled_on date,odometer_value numeric,estimated_cost_value numeric,actual_cost_value numeric,status_value text,completed_on date) returns uuid language plpgsql security invoker set search_path=public as $$
declare result_id uuid; target_truck_id uuid; target_vendor_id uuid;
begin
 if not private.has_company_role(target_company_id,array['owner','administrator','fleet_manager']::public.member_role[]) then raise exception 'Maintenance access required'; end if;
 if trim(reference_value)='' or trim(target_unit_number)='' or trim(description_value)='' or scheduled_on is null or odometer_value<0 or estimated_cost_value<0 or actual_cost_value<0 or status_value not in ('scheduled','in_progress','completed','cancelled') or (status_value='completed' and completed_on is null) then raise exception 'Invalid work order'; end if;
 select id into target_truck_id from public.trucks where company_id=target_company_id and lower(unit_number)=lower(trim(target_unit_number)); if target_truck_id is null then raise exception 'Truck unit not found'; end if;
 if nullif(trim(vendor_name),'') is not null then select id into target_vendor_id from public.vendors where company_id=target_company_id and lower(name)=lower(trim(vendor_name)) limit 1; if target_vendor_id is null then insert into public.vendors(company_id,name) values(target_company_id,trim(vendor_name)) returning id into target_vendor_id; end if; end if;
 if exists(select 1 from public.work_orders where company_id=target_company_id and lower(details->>'reference')=lower(trim(reference_value)) and id is distinct from target_order_id) then raise exception 'Work order reference already exists'; end if;
 if target_order_id is null then insert into public.work_orders(company_id,truck_id,assigned_vendor_id,issue,status,opened_at,completed_at,details) values(target_company_id,target_truck_id,target_vendor_id,trim(description_value),status_value,scheduled_on,completed_on,jsonb_build_object('reference',trim(reference_value),'serviceType',service_type_value,'scheduledDate',scheduled_on,'odometer',odometer_value,'estimatedCost',estimated_cost_value,'actualCost',actual_cost_value)) returning id into result_id;
 else update public.work_orders set truck_id=target_truck_id,assigned_vendor_id=target_vendor_id,issue=trim(description_value),status=status_value,opened_at=scheduled_on,completed_at=completed_on,details=jsonb_build_object('reference',trim(reference_value),'serviceType',service_type_value,'scheduledDate',scheduled_on,'odometer',odometer_value,'estimatedCost',estimated_cost_value,'actualCost',actual_cost_value) where id=target_order_id and company_id=target_company_id returning id into result_id; if result_id is null then raise exception 'Work order not found'; end if; end if;
 return result_id;
end $$;
revoke all on function public.save_work_order(uuid,uuid,text,text,text,text,text,date,numeric,numeric,numeric,text,date) from public,anon;
grant execute on function public.save_work_order(uuid,uuid,text,text,text,text,text,date,numeric,numeric,numeric,text,date) to authenticated;
