"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {readAllPages} from "@/lib/read-all-pages";
import {createClient} from "@/lib/supabase/server";
import {JournalDraft,JournalEntry,validateJournal} from "@/lib/accounting";
async function context(companyId:string,readOnly=false){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator","accountant",...(readOnly?["auditor"]:[])].includes(String(m.role)))throw new Error("Accounting access required.");return s}
const numberValue=(value:string)=>{const found=value.match(/\d+/);if(!found)throw new Error("Journal number must include a number.");return Number(found[0])};
export async function listJournalEntries(companyId:string):Promise<JournalEntry[]>{const s=await context(companyId,true);
const [data,lines]=await Promise.all([
 readAllPages<any>((after,limit)=>{let q=s.from("journal_entries").select("id,entry_number,entry_date,memo,status,posted_at,reverses_entry_id").eq("company_id",companyId).order("id").limit(limit);if(after)q=q.gt("id",after);return q}),
 readAllPages<any>((after,limit)=>{let q=s.from("journal_lines").select("id,journal_entry_id,description,debit,credit,account:chart_of_accounts(account_number,name)").eq("company_id",companyId).order("id").limit(limit);if(after)q=q.gt("id",after);return q})
]);const grouped=new Map<string,any[]>();for(const line of lines){const bucket=grouped.get(line.journal_entry_id);if(bucket)bucket.push(line);else grouped.set(line.journal_entry_id,[line])}
const reversedIds=new Set((data??[]).map(x=>x.reverses_entry_id).filter(Boolean));return(data??[]).map((x:any)=>({id:x.id,number:`JE-${x.entry_number}`,date:x.entry_date,memo:x.memo,status:reversedIds.has(x.id)?"Reversed":x.status==="posted"?"Posted":"Draft",postedAt:String(x.posted_at??""),reversalOf:String(x.reverses_entry_id??""),lines:(grouped.get(x.id)??[]).map((l:any)=>{const a=Array.isArray(l.account)?l.account[0]:l.account;return{id:l.id,account:`${a?.account_number??""} · ${a?.name??"Unknown"}`,description:String(l.description??""),debit:Number(l.debit),credit:Number(l.credit)}})}))}
export async function saveJournalEntry(companyId:string,draft:JournalDraft,entries:JournalEntry[],status:"Draft"|"Posted",id?:string):Promise<JournalEntry>{if(status==="Posted"){const e=validateJournal(draft,entries,id);if(Object.keys(e).length)throw new Error(Object.values(e)[0])}const s=await context(companyId),{data,error}=await s.rpc("save_journal_entry",{target_company_id:companyId,target_entry_id:id??null,entry_number_value:numberValue(draft.number),entry_date_value:draft.date,memo_value:draft.memo,lines_value:draft.lines,post_now:status==="Posted"});if(error)throw new Error(error.message);return{...draft,id:String(data),status,postedAt:status==="Posted"?new Date().toISOString():"",reversalOf:""}}
export async function reverseJournalEntry(companyId:string,entry:JournalEntry,newNumber:string,date:string):Promise<JournalEntry>{const s=await context(companyId),{data,error}=await s.rpc("reverse_journal_entry",{target_company_id:companyId,target_entry_id:entry.id,new_entry_number:numberValue(newNumber),reversal_date:date});if(error)throw new Error(error.message);return{id:String(data),number:newNumber,date,memo:`Reversal of ${entry.number}: ${entry.memo}`,status:"Posted",postedAt:new Date().toISOString(),reversalOf:entry.id,lines:entry.lines.map(l=>({...l,id:crypto.randomUUID(),debit:l.credit,credit:l.debit}))}}
export async function deleteJournalEntry(companyId:string,id:string){const s=await context(companyId),{error}=await s.from("journal_entries").delete().eq("company_id",companyId).eq("id",id).eq("status","draft");if(error)throw new Error(error.message)}
