"use server";
import {readQueryRows} from "@/lib/read-query-rows";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from "@/lib/supabase/server";
import {ApprovalItem} from "@/lib/approvals";
async function context(companyId:string){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator","accountant","dispatcher","fleet_manager","payroll_manager"].includes(String(m.role)))throw new Error("Approval access required.");return s}
const statusMap:Record<string,ApprovalItem["status"]>={pending:"Pending",approved:"Approved",rejected:"Rejected"};
export async function listApprovals(companyId:string):Promise<ApprovalItem[]>{const s=await context(companyId),{data,error}=await readQueryRows(offset=>s.from("approvals").select("id,record_type,record_id,status,decision_notes,decided_at,created_at,metadata,requester:profiles!approvals_requested_by_fkey(full_name),reviewer:profiles!approvals_assigned_to_fkey(full_name)").eq("company_id",companyId).order("created_at",{ascending:false}).order("id").range(offset,offset+499));if(error)throw new Error(error.message);return(data??[]).map((x:any)=>{const m=x.metadata??{},requester=Array.isArray(x.requester)?x.requester[0]:x.requester,reviewer=Array.isArray(x.reviewer)?x.reviewer[0]:x.reviewer;return{id:x.id,type:m.type??x.record_type,reference:m.reference??String(x.record_id).slice(0,8),submittedBy:String(requester?.full_name??"Unknown"),submittedAt:x.created_at,amount:Number(m.amount??0),description:String(m.description??x.record_type),status:statusMap[x.status]??"Pending",reviewedBy:String(reviewer?.full_name??""),reviewedAt:String(x.decided_at??""),note:String(x.decision_notes??""),flags:Array.isArray(m.flags)?m.flags.map(String):[]}})}
export async function reviewApproval(companyId:string,item:ApprovalItem,status:"Approved"|"Rejected",note:string):Promise<ApprovalItem>{const s=await context(companyId),{error}=await s.rpc("decide_approval",{target_company_id:companyId,target_approval_id:item.id,decision:status.toLowerCase(),review_note:note});if(error)throw new Error(error.message);const{data:identity}=await s.auth.getClaims();const{data:profile}=await s.from("profiles").select("full_name").eq("id",String(identity?.claims?.sub??"")).maybeSingle();return{...item,status,note:note.trim(),reviewedBy:profile?.full_name??"Current user",reviewedAt:new Date().toISOString()}}
