"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createHash} from "node:crypto";
import {createClient} from "@/lib/supabase/server";
import {BankingWorkspaceData,parseBankStatementCsv} from "@/lib/banking";

async function context(companyId:string){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator","accountant"].includes(String(m.role)))throw new Error("Finance access required.");return s}
const relation=(value:any)=>Array.isArray(value)?value[0]:value;

export async function listBankingWorkspace(companyId:string):Promise<BankingWorkspaceData>{const s=await context(companyId);const[accountsResult,ledgerResult,transactionsResult,journalsResult,reconciliationsResult,importsResult]=await Promise.all([
  s.from("bank_accounts").select("id,name,account_type,ledger_account_id,ledger:chart_of_accounts(account_number,name)").eq("company_id",companyId).eq("active",true).order("name"),
  s.from("chart_of_accounts").select("id,account_number,name").eq("company_id",companyId).eq("account_type","asset").eq("active",true).order("account_number"),
  s.from("imported_transactions").select("id,bank_account_id,posted_on,description,amount,review_status,matched_id,review_note,reconciliation_id").eq("company_id",companyId).order("posted_on",{ascending:false}).limit(1000),
  s.from("journal_entries").select("id,entry_number,entry_date,memo,status,lines:journal_lines(account_id,debit,credit)").eq("company_id",companyId).eq("status","posted").order("entry_date",{ascending:false}).limit(1000),
  s.from("reconciliations").select("id,bank_account_id,statement_starts_on,statement_ends_on,statement_balance,reconciled_balance,status,locked_at").eq("company_id",companyId).order("statement_ends_on",{ascending:false}).limit(24),
  s.from("bank_statement_imports").select("id,bank_account_id,original_name,row_count,imported_count,duplicate_count,created_at").eq("company_id",companyId).order("created_at",{ascending:false}).limit(12)
]);
  for(const result of [accountsResult,ledgerResult,transactionsResult,journalsResult,reconciliationsResult,importsResult])if(result.error)throw new Error(result.error.message);
  const accounts=(accountsResult.data??[]).map((x:any)=>{const ledger=relation(x.ledger);return{id:String(x.id),name:String(x.name),accountType:String(x.account_type),ledgerAccountId:String(x.ledger_account_id??""),ledgerAccount:`${ledger?.account_number??""} · ${ledger?.name??"Unlinked"}`}});
  const candidates=(journalsResult.data??[]).flatMap((journal:any)=>accounts.flatMap(account=>{const amount=Math.round((journal.lines??[]).filter((line:any)=>line.account_id===account.ledgerAccountId).reduce((sum:number,line:any)=>sum+Number(line.debit)-Number(line.credit),0)*100)/100;return amount?[{id:String(journal.id),bankAccountId:account.id,date:String(journal.entry_date),label:`JE-${journal.entry_number} · ${journal.entry_date} · ${journal.memo}`,amount}]:[]}));
  return{accounts,ledgerAccounts:(ledgerResult.data??[]).map((x:any)=>({id:String(x.id),label:`${x.account_number} · ${x.name}`})),candidates,
    transactions:(transactionsResult.data??[]).map((x:any)=>({id:String(x.id),bankAccountId:String(x.bank_account_id),postedOn:String(x.posted_on),description:String(x.description),amount:Number(x.amount),status:x.review_status,matchedId:String(x.matched_id??""),note:String(x.review_note??""),reconciliationId:String(x.reconciliation_id??"")})),
    reconciliations:(reconciliationsResult.data??[]).map((x:any)=>({id:String(x.id),bankAccountId:String(x.bank_account_id),startsOn:String(x.statement_starts_on),endsOn:String(x.statement_ends_on),statementBalance:Number(x.statement_balance),bookBalance:Number(x.reconciled_balance),status:x.status,lockedAt:String(x.locked_at??"")})),
    imports:(importsResult.data??[]).map((x:any)=>({id:String(x.id),bankAccountId:String(x.bank_account_id),originalName:String(x.original_name),rowCount:Number(x.row_count),importedCount:Number(x.imported_count),duplicateCount:Number(x.duplicate_count),createdAt:String(x.created_at)}))};
}

export async function createBankAccount(companyId:string,name:string,type:string,ledgerAccountId:string){const s=await context(companyId);const{error}=await s.rpc("create_bank_account",{target_company_id:companyId,account_name:name,account_type_value:type,ledger_account_value:ledgerAccountId});if(error)throw new Error(error.message)}

export async function importBankStatement(companyId:string,formData:FormData){const bankAccountId=String(formData.get("bankAccountId")??""),file=formData.get("statement");if(!(file instanceof File)||file.size===0)throw new Error("Choose a CSV statement.");if(file.size>1024*1024)throw new Error("The CSV file must be 1 MB or smaller.");if(!file.name.toLowerCase().endsWith(".csv"))throw new Error("Choose a .csv file.");const parsed=parseBankStatementCsv(await file.text()),occurrences=new Map<string,number>();const rows=parsed.map(row=>{const base=[bankAccountId,row.reference||row.postedOn,row.reference?"":row.description.trim().toLowerCase(),row.reference?"":row.amount.toFixed(2)].join("|");const occurrence=(occurrences.get(base)??0)+1;occurrences.set(base,occurrence);return{...row,hash:createHash("sha256").update(`${base}|${occurrence}`).digest("hex")}});const s=await context(companyId),{data,error}=await s.rpc("import_bank_statement",{target_company_id:companyId,target_bank_account_id:bankAccountId,original_name_value:file.name,rows_value:rows});if(error)throw new Error(error.message);return data as {rowCount:number;importedCount:number;duplicateCount:number}}

export async function reviewBankTransaction(companyId:string,transactionId:string,action:"match"|"exclude"|"unmatch",journalEntryId?:string,note?:string){const s=await context(companyId),{error}=await s.rpc("review_bank_transaction",{target_company_id:companyId,target_transaction_id:transactionId,review_action:action,target_journal_entry_id:journalEntryId||null,note_value:note||null});if(error)throw new Error(error.message)}
export async function saveBankReconciliation(companyId:string,bankAccountId:string,startsOn:string,endsOn:string,statementBalance:number){const s=await context(companyId),{error}=await s.rpc("save_bank_reconciliation",{target_company_id:companyId,target_bank_account_id:bankAccountId,starts_on_value:startsOn,ends_on_value:endsOn,statement_balance_value:statementBalance});if(error)throw new Error(error.message)}
export async function completeBankReconciliation(companyId:string,reconciliationId:string){const s=await context(companyId),{error}=await s.rpc("complete_bank_reconciliation",{target_company_id:companyId,target_reconciliation_id:reconciliationId});if(error)throw new Error(error.message)}
