"use server";
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import {createClient} from "@/lib/supabase/server";
import {periodChange} from "@/lib/calculations";
export type DashboardData={stats:{label:string;value:string;change:string}[];cashFlow:{month:string;income:number;expenses:number}[];fleet:{totalMileage:number;loadedMileage:number;revenuePerMile:number;costPerMile:number;fuelCost:number;fuelPerMile:number} ;loads:{number:string;lane:string;driver:string;unit:string;value:string;status:string}[];alerts:{title:string;detail:string;urgency:string;target:string;kind:"approval"|"maintenance"|"fleet"}[];recent:{title:string;detail:string;amount:string;status:string;kind:"income"|"expense"}[]};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}),precise=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const statusLabel=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export async function loadDashboard(companyId:string):Promise<DashboardData>{const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data:claims,error:authError}=await s.auth.getClaims(),uid=claims?.claims?.sub;if(authError||typeof uid!=="string")throw new Error("Authentication required.");const{data:membership}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!membership)throw new Error("Dashboard access required.");const now=new Date(),monthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)),previousMonthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-1,1)),sixStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-5,1)),iso=(d:Date)=>d.toISOString().slice(0,10);
 const results=await Promise.all([
  s.from("income").select("id,received_on,description,amount,status,customer:customers(name)").eq("company_id",companyId).gte("received_on",iso(sixStart)).order("received_on",{ascending:false}),
  s.from("expenses").select("id,occurred_on,description,amount,status,vendor:vendors(name)").eq("company_id",companyId).gte("occurred_on",iso(sixStart)).order("occurred_on",{ascending:false}),
  s.from("invoices").select("id,status,total,due_on").eq("company_id",companyId).neq("status","paid"),
  s.from("loads").select("load_number,status,customer_rate,driver_pay,actual_miles,planned_miles,fees,truck:trucks(unit_number),driver:drivers(profile:profiles(full_name)),route:routes(origin,destination)").eq("company_id",companyId).not("status","in","(paid,cancelled)").order("created_at",{ascending:false}).limit(5),
  s.from("fuel_entries").select("purchased_at,total_cost").eq("company_id",companyId).gte("purchased_at",iso(monthStart)),
  s.from("mileage_logs").select("total_miles,loaded_miles").eq("company_id",companyId).gte("started_at",iso(monthStart)),
  s.from("approvals").select("id,metadata").eq("company_id",companyId).eq("status","pending"),
  s.from("maintenance_schedules").select("service_type,next_due_on,next_due_odometer,truck:trucks(unit_number,current_odometer)").eq("company_id",companyId).eq("active",true).order("next_due_on").limit(5),
  s.from("trucks").select("unit_number,insurance_expires_on,registration_expires_on,inspection_expires_on").eq("company_id",companyId)
 ]);for(const result of results)if(result.error)throw new Error(result.error.message);const[income,expenses,invoices,activeLoads,fuel,mileage,approvals,schedules,trucks]=results.map(r=>r.data??[]);
 const currentIncome=(income as any[]).filter(x=>x.received_on>=iso(monthStart)).reduce((n,x)=>n+Number(x.amount),0),currentExpenses=(expenses as any[]).filter(x=>x.occurred_on>=iso(monthStart)).reduce((n,x)=>n+Number(x.amount),0),previousIncome=(income as any[]).filter(x=>x.received_on>=iso(previousMonthStart)&&x.received_on<iso(monthStart)).reduce((n,x)=>n+Number(x.amount),0),previousExpenses=(expenses as any[]).filter(x=>x.occurred_on>=iso(previousMonthStart)&&x.occurred_on<iso(monthStart)).reduce((n,x)=>n+Number(x.amount),0),outstanding=(invoices as any[]).reduce((n,x)=>n+Number(x.total),0);
 const cashFlow=Array.from({length:6},(_,index)=>{const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-5+index,1)),next=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,1)),start=iso(date),end=iso(next);return{month:date.toLocaleString("en-US",{month:"short",timeZone:"UTC"}),income:(income as any[]).filter(x=>x.received_on>=start&&x.received_on<end).reduce((n,x)=>n+Number(x.amount),0)/1000,expenses:(expenses as any[]).filter(x=>x.occurred_on>=start&&x.occurred_on<end).reduce((n,x)=>n+Number(x.amount),0)/1000}});
 const totalMileage=(mileage as any[]).reduce((n,x)=>n+Number(x.total_miles??0),0),loadedMileage=(mileage as any[]).reduce((n,x)=>n+Number(x.loaded_miles??0),0),fuelCost=(fuel as any[]).reduce((n,x)=>n+Number(x.total_cost),0),loadRevenue=(activeLoads as any[]).reduce((n,x)=>n+Number(x.customer_rate),0),loadPay=(activeLoads as any[]).reduce((n,x)=>n+Number(x.driver_pay),0);
 const loads=(activeLoads as any[]).map(x=>{const route=Array.isArray(x.route)?x.route[0]:x.route,driver=Array.isArray(x.driver)?x.driver[0]:x.driver,profile=Array.isArray(driver?.profile)?driver.profile[0]:driver?.profile,truck=Array.isArray(x.truck)?x.truck[0]:x.truck,origin=route?.origin?.label??x.fees?.pickup_location??"Origin",destination=route?.destination?.label??x.fees?.delivery_location??"Destination";return{number:x.load_number,lane:`${origin} → ${destination}`,driver:profile?.full_name??x.fees?.driver_name??"Unassigned",unit:truck?.unit_number??"—",value:money.format(Number(x.customer_rate)),status:statusLabel(x.status)}});
 const alerts:DashboardData["alerts"]=[];if(approvals.length)alerts.push({title:`${approvals.length} item${approvals.length===1?"":"s"} need review`,detail:"Pending approval queue",urgency:"Today",target:"Approvals",kind:"approval"});for(const schedule of (schedules as any[]).slice(0,2)){const truck=Array.isArray(schedule.truck)?schedule.truck[0]:schedule.truck,remaining=Number(schedule.next_due_odometer??0)-Number(truck?.current_odometer??0);if(schedule.next_due_on||remaining<=1000)alerts.push({title:`Unit ${truck?.unit_number??"—"} service due`,detail:schedule.next_due_on?`${schedule.service_type} · ${schedule.next_due_on}`:`${Math.max(0,remaining).toLocaleString()} miles remaining`,urgency:"Soon",target:"Maintenance",kind:"maintenance"})}for(const truck of trucks as any[]){const expirations=[truck.insurance_expires_on,truck.registration_expires_on,truck.inspection_expires_on].filter(Boolean).sort();if(expirations[0]&&Date.parse(expirations[0])-now.getTime()<=30*86400000)alerts.push({title:`Unit ${truck.unit_number} document expires`,detail:expirations[0],urgency:"30 days",target:"Fleet",kind:"fleet"})}
 const recent=[...(income as any[]).map(x=>({date:x.received_on,title:(Array.isArray(x.customer)?x.customer[0]:x.customer)?.name??x.description,detail:x.description,amount:`+${precise.format(Number(x.amount))}`,status:statusLabel(x.status),kind:"income" as const})),...(expenses as any[]).map(x=>({date:x.occurred_on,title:(Array.isArray(x.vendor)?x.vendor[0]:x.vendor)?.name??x.description,detail:x.description,amount:`−${precise.format(Number(x.amount))}`,status:statusLabel(x.status),kind:"expense" as const}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(({date:_,...item})=>item);
 return{stats:[{label:"Total income",value:money.format(currentIncome),change:periodChange(currentIncome,previousIncome)},{label:"Total expenses",value:money.format(currentExpenses),change:periodChange(currentExpenses,previousExpenses)},{label:"Estimated net profit",value:money.format(currentIncome-currentExpenses),change:periodChange(currentIncome-currentExpenses,previousIncome-previousExpenses)},{label:"Outstanding invoices",value:money.format(outstanding),change:`${invoices.length} invoice${invoices.length===1?"":"s"}`}],cashFlow,fleet:{totalMileage,loadedMileage,revenuePerMile:totalMileage?loadRevenue/totalMileage:0,costPerMile:totalMileage?(fuelCost+loadPay+currentExpenses)/totalMileage:0,fuelCost,fuelPerMile:totalMileage?fuelCost/totalMileage:0},loads,alerts:alerts.slice(0,4),recent}}
