"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from "@/lib/supabase/server";
import {DriverFuel,TripDraft,validateDriverFuel,validateTrip} from "@/lib/driver";
export type DriverPortalData={driverId:string;name:string;initials:string;loadId:string;loadNumber:string;status:string;origin:string;destination:string;pickupDetail:string;deliveryDetail:string;unit:string;trailer:string;vehicle:string;odometer:number;nextService:number;receipts:string[]};
async function context(){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:driver,error:driverError}=await s.from("drivers").select("id,company_id,profile:profiles(full_name)").eq("profile_id",uid).eq("status","active").maybeSingle();if(driverError)throw new Error(driverError.message);if(!driver)throw new Error("An active driver profile is required.");return{s,uid,driver}}
export async function loadDriverPortal():Promise<DriverPortalData>{const{s,driver}=await context(),{data:loads,error}=await s.from("loads").select("id,load_number,status,fees,truck:trucks(id,unit_number,year,make,model,current_odometer),trailer:trailers(unit_number),route:routes(origin,destination)").eq("driver_id",driver.id).not("status","in","(paid,cancelled,delivered)").order("created_at",{ascending:false}).limit(1);if(error)throw new Error(error.message);const load=loads?.[0];if(!load){const profile=Array.isArray(driver.profile)?driver.profile[0]:driver.profile;return{driverId:driver.id,name:profile?.full_name??"Driver",initials:"DR",loadId:"",loadNumber:"—",status:"unassigned",origin:"Origin",destination:"Destination",pickupDetail:"No active load assigned",deliveryDetail:"No active load assigned",unit:"—",trailer:"—",vehicle:"No assigned truck",odometer:0,nextService:0,receipts:[]}}const truck=Array.isArray(load.truck)?load.truck[0]:load.truck,trailer=Array.isArray(load.trailer)?load.trailer[0]:load.trailer,route=Array.isArray(load.route)?load.route[0]:load.route,profile=Array.isArray(driver.profile)?driver.profile[0]:driver.profile;const{data:schedules}=await s.from("maintenance_schedules").select("next_due_odometer").eq("truck_id",truck?.id??"").eq("active",true).order("next_due_odometer").limit(1),{data:receipts}=await s.from("receipts").select("created_at,document:documents(original_name)").eq("company_id",driver.company_id).eq("load_id",load.id).order("created_at",{ascending:false});const name=profile?.full_name??"Driver";return{driverId:driver.id,name,initials:name.split(/\s+/).map((x:string)=>x[0]).slice(0,2).join("").toUpperCase(),loadId:load.id,loadNumber:load.load_number,status:load.status.replaceAll("_"," "),origin:route?.origin?.label??load.fees?.pickup_location??"Origin",destination:route?.destination?.label??load.fees?.delivery_location??"Destination",pickupDetail:load.fees?.pickup_detail??"Pickup assigned",deliveryDetail:load.fees?.delivery_detail??"Delivery assigned",unit:truck?.unit_number??"—",trailer:trailer?.unit_number??"—",vehicle:[truck?.year,truck?.make,truck?.model].filter(Boolean).join(" ")||"Assigned truck",odometer:Number(truck?.current_odometer??0),nextService:Number(schedules?.[0]?.next_due_odometer??0),receipts:(receipts??[]).map((x:any)=>`${(Array.isArray(x.document)?x.document[0]:x.document)?.original_name??"Receipt"} · ${new Date(x.created_at).toLocaleString()}`)}}
export async function submitDriverTrip(loadId:string,draft:TripDraft,expectedDriverId:string,requestId:string){const errors=validateTrip(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const{s,driver}=await context();if(driver.id!==expectedDriverId)throw new Error("The signed-in driver has changed. Reload before submitting.");const{error}=await s.rpc("submit_driver_submission",{request_id_value:requestId,driver_id_value:expectedDriverId,load_id_value:loadId,kind_value:"trip",payload_value:draft});if(error)throw new Error(error.message)}
export async function submitDriverFuel(loadId:string,value:DriverFuel,expectedDriverId:string,requestId:string){const errors=validateDriverFuel(value);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const{s,driver}=await context();if(driver.id!==expectedDriverId)throw new Error("The signed-in driver has changed. Reload before submitting.");const{error}=await s.rpc("submit_driver_submission",{request_id_value:requestId,driver_id_value:expectedDriverId,load_id_value:loadId,kind_value:"fuel",payload_value:value});if(error)throw new Error(error.message)}
export async function uploadDriverReceipt(loadId:string,formData:FormData){const{s,uid,driver}=await context(),file=formData.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Choose a receipt image or PDF.");if(file.size>4*1024*1024)throw new Error("Receipt files must be 4 MB or smaller.");if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error("Use a JPEG, PNG, WebP, or PDF receipt.");const path=`${driver.company_id}/${uid}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`,{error:uploadError}=await s.storage.from("receipts").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw new Error(uploadError.message);const{error:recordError}=await s.rpc("record_driver_receipt",{target_load_id:loadId,bucket_value:"receipts",path_value:path,name_value:file.name,mime_value:file.type,size_value:file.size});if(recordError){await s.storage.from("receipts").remove([path]);throw new Error(recordError.message)}return`${file.name} · ${new Date().toLocaleString()}`}
export async function reportDriverIssue(loadId:string,issue:string){const{s}=await context(),{error}=await s.rpc("report_driver_vehicle_issue",{target_load_id:loadId,issue_value:issue});if(error)throw new Error(error.message)}
