"use server";
import {createClient} from "@/lib/supabase/server";
import {readQueryRows} from "@/lib/read-query-rows";
export type LedgerAccount={id:string;number:string;name:string;type:string;active:boolean};
export type AccountingPeriod={id:string;start:string;end:string;closed:boolean};
async function context(companyId:string,read=false){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const {data,error}=await s.auth.getClaims();const uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const {data:m,error:e}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(e||!m||!["owner","administrator","accountant",...(read?["auditor"]:[])].includes(m.role))throw new Error("Accounting access required.");return s}
export async function listLedgerAccounts(companyId:string):Promise<LedgerAccount[]>{const s=await context(companyId,true);const {data}=await readQueryRows(offset=>s.from("chart_of_accounts").select("id,account_number,name,account_type,active").eq("company_id",companyId).order("account_number").order("id").range(offset,offset+499));return data.map(x=>({id:x.id,number:x.account_number,name:x.name,type:x.account_type,active:x.active}))}
export async function saveLedgerAccount(companyId:string,value:Omit<LedgerAccount,"id">,id?:string){const s=await context(companyId);const {error}=await s.rpc("manage_ledger_account",{target_company_id:companyId,target_account_id:id??null,number_value:value.number,name_value:value.name,type_value:value.type,active_value:value.active});if(error)throw new Error(error.message)}
export async function listAccountingPeriods(companyId:string):Promise<AccountingPeriod[]>{const s=await context(companyId,true);const {data}=await readQueryRows(offset=>s.from("accounting_periods").select("id,starts_on,ends_on,closed_at").eq("company_id",companyId).order("starts_on",{ascending:false}).order("id").range(offset,offset+499));return data.map(x=>({id:x.id,start:x.starts_on,end:x.ends_on,closed:!!x.closed_at}))}
export async function setAccountingPeriod(companyId:string,start:string,end:string,closed:boolean){const s=await context(companyId);const {error}=await s.rpc("set_accounting_period_closed",{target_company_id:companyId,start_date:start,end_date:end,closed_value:closed});if(error)throw new Error(error.message)}
export async function reverseMoneyRecord(companyId:string,kind:"income"|"expense"|"settlement",id:string,date:string,reason:string){const s=await context(companyId);const {error}=await s.rpc("reverse_money_record",{target_company_id:companyId,record_kind:kind,target_record_id:id,reversal_date:date,reason_value:reason});if(error)throw new Error(error.message)}
