"use server";
import {createClient} from "@/lib/supabase/server";
import {Vehicle,VehicleDraft,validateVehicle} from "@/lib/fleet";
const toDb:Record<VehicleDraft["status"],string>={Active:"active","Out of service":"out_of_service",Sold:"sold"};const fromDb:Record<string,VehicleDraft["status"]>={active:"Active",out_of_service:"Out of service",sold:"Sold"};
async function context(companyId:string,allowed=["owner","administrator","fleet_manager"]){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const{data:membership}=await supabase.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();if(!membership||!allowed.includes(String(membership.role)))throw new Error("Fleet access required.");return supabase}
function scheduleMileage(value:unknown){const rows=Array.isArray(value)?value:[];const schedule=rows.find(x=>x&&typeof x==="object"&&"service_type" in x&&x.service_type==="General service");return Number(schedule?.next_due_odometer??0)}
export async function listVehicles(companyId:string):Promise<Vehicle[]>{const supabase=await context(companyId);const[trucks,trailers]=await Promise.all([supabase.from("trucks").select("id,unit_number,year,make,model,vin,current_odometer,status,schedules:maintenance_schedules(service_type,next_due_odometer)").eq("company_id",companyId),supabase.from("trailers").select("id,unit_number,year,make,model,vin,status,schedules:maintenance_schedules(service_type,next_due_odometer)").eq("company_id",companyId)]);if(trucks.error)throw new Error(trucks.error.message);if(trailers.error)throw new Error(trailers.error.message);return[...(trucks.data??[]).map(x=>({id:`Truck:${x.id}`,unit:String(x.unit_number),type:"Truck" as const,year:Number(x.year??new Date().getFullYear()),make:String(x.make??"Unknown"),model:String(x.model??"Unknown"),vin:String(x.vin??""),odometer:Number(x.current_odometer),nextServiceOdometer:scheduleMileage(x.schedules),status:fromDb[String(x.status)]??"Active"})),...(trailers.data??[]).map(x=>({id:`Trailer:${x.id}`,unit:String(x.unit_number),type:"Trailer" as const,year:Number(x.year??new Date().getFullYear()),make:String(x.make??"Unknown"),model:String(x.model??"Unknown"),vin:String(x.vin??""),odometer:0,nextServiceOdometer:scheduleMileage(x.schedules),status:fromDb[String(x.status)]??"Active"}))]}
export async function saveVehicle(companyId:string,draft:VehicleDraft,records:Vehicle[],id?:string):Promise<Vehicle>{const errors=validateVehicle(draft,records,id);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,["owner","administrator"]);const[existingType,rawId]=id?.split(":")??[];if(existingType&&existingType!==draft.type)throw new Error("Vehicle type cannot be changed after creation.");const{data,error}=await supabase.rpc("save_vehicle",{target_company_id:companyId,target_vehicle_id:rawId??null,vehicle_type:draft.type,target_unit_number:draft.unit,model_year:draft.year,make_name:draft.make,model_name:draft.model,vin_value:draft.vin,odometer_value:draft.odometer,next_service_odometer_value:draft.nextServiceOdometer,status_value:toDb[draft.status]});if(error)throw new Error(error.message);return{...draft,id:`${draft.type}:${data}`}}
export async function deleteVehicle(companyId:string,record:Vehicle){const supabase=await context(companyId);const[type,id]=record.id.split(":");if(!id||type!==record.type)throw new Error("Invalid vehicle reference.");const{error}=await supabase.rpc("delete_vehicle",{target_company_id:companyId,target_vehicle_id:id,vehicle_type:type});if(error)throw new Error(error.message)}
