"use server";
import {createClient} from "@/lib/supabase/server";
import {Invoice,InvoiceDraft,InvoiceStatus,validateInvoice} from "@/lib/invoices";
const toDb:Record<InvoiceStatus,string>={Draft:"draft",Sent:"sent",Overdue:"overdue",Paid:"paid"};const fromDb:Record<string,InvoiceStatus>={draft:"Draft",sent:"Sent",overdue:"Overdue",paid:"Paid"};
async function context(companyId:string){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const{data:membership}=await supabase.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();if(!membership||!["owner","administrator","accountant"].includes(String(membership.role)))throw new Error("Finance access required.");return supabase}
function nameOf(value:unknown){if(Array.isArray(value))return String(value[0]?.name??"Customer");if(value&&typeof value==="object"&&"name" in value)return String(value.name);return"Customer"}
export async function listInvoices(companyId:string):Promise<Invoice[]>{const supabase=await context(companyId);const{data,error}=await supabase.from("invoices").select("id,invoice_number,issued_on,due_on,status,notes,customer:customers(name),items:invoice_items(id,description,quantity,unit_price,tax_rate,sort_order)").eq("company_id",companyId).order("issued_on",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(row=>({id:String(row.id),number:`INV-${row.invoice_number}`,customer:nameOf(row.customer),issuedOn:String(row.issued_on),dueOn:String(row.due_on),status:fromDb[String(row.status)]??"Draft",notes:String(row.notes??""),items:(Array.isArray(row.items)?row.items:[]).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)).map(item=>({id:String(item.id),description:String(item.description),quantity:Number(item.quantity),unitPrice:Number(item.unit_price),taxRate:Number(item.tax_rate)}))}))}
export async function saveInvoice(companyId:string,draft:InvoiceDraft,id?:string):Promise<Invoice>{const errors=validateInvoice(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId);const{data,error}=await supabase.rpc("save_invoice",{target_company_id:companyId,target_invoice_id:id??null,customer_name:draft.customer,issued_date:draft.issuedOn,due_date:draft.dueOn,invoice_status:toDb[draft.status],invoice_notes:draft.notes,line_items:draft.items});if(error)throw new Error(error.message);const result=Array.isArray(data)?data[0]:data;if(!result)throw new Error("Invoice was not saved.");return{...draft,id:String(result.id),number:`INV-${result.invoice_number}`}}
export async function deleteInvoice(companyId:string,id:string){const supabase=await context(companyId);const{data,error:readError}=await supabase.from("invoices").select("status").eq("company_id",companyId).eq("id",id).maybeSingle();if(readError)throw new Error(readError.message);if(!data)throw new Error("Invoice not found.");if(data.status==="paid")throw new Error("Paid invoices require a credit note or adjustment.");const{error}=await supabase.from("invoices").delete().eq("company_id",companyId).eq("id",id);if(error)throw new Error(error.message)}
