"use server";
import {readQueryRows} from "@/lib/read-query-rows";
import {createClient} from "@/lib/supabase/server";
import {LoadDraft,LoadRecord,LoadStatus,validateLoad} from "@/lib/operations";
const toDb:Record<LoadStatus,string>={Ready:"planned",Dispatched:"dispatched","In transit":"in_transit",Delivered:"delivered"};const fromDb:Record<string,LoadStatus>={planned:"Ready",dispatched:"Dispatched",in_transit:"In transit",at_delivery:"In transit",delivered:"Delivered",invoiced:"Delivered",paid:"Delivered",cancelled:"Ready"};
async function context(companyId:string){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const{data:membership}=await supabase.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();if(!membership||!["owner","administrator","dispatcher"].includes(String(membership.role)))throw new Error("Dispatch access required.");return supabase}
function relatedName(value:unknown,key:string,fallback:string){if(Array.isArray(value))return String(value[0]?.[key]??fallback);if(value&&typeof value==="object"&&key in value)return String((value as Record<string,unknown>)[key]??fallback);return fallback}
export async function listLoads(companyId:string):Promise<LoadRecord[]>{const supabase=await context(companyId);const{data,error}=await readQueryRows(offset=>supabase.from("loads").select("accounting:invoices(id),id,load_number,status,customer_rate,planned_miles,fees,customer:customers(name),truck:trucks(unit_number),driver:drivers(profile:profiles(full_name)),route:routes(origin,destination)").eq("company_id",companyId).order("id").range(offset,offset+499));if(error)throw new Error(error.message);return(data??[]).map(row=>{const fees=(row.fees&&typeof row.fees==="object"?row.fees:{}) as Record<string,unknown>;const route=Array.isArray(row.route)?row.route[0]:row.route;const origin=route&&typeof route==="object"&&"origin" in route?(route.origin as Record<string,unknown>)?.label:"";const destination=route&&typeof route==="object"&&"destination" in route?(route.destination as Record<string,unknown>)?.label:"";const driver=Array.isArray(row.driver)?row.driver[0]:row.driver;const profile=driver&&typeof driver==="object"&&"profile" in driver?(Array.isArray(driver.profile)?driver.profile[0]:driver.profile):null;return{accountingPosted:!!row.accounting?.length,id:String(row.id),number:String(row.load_number),origin:String(origin??""),destination:String(destination??""),customer:relatedName(row.customer,"name","Customer"),driver:relatedName(profile,"full_name",String(fees.driver_name??"Unassigned")),unit:relatedName(row.truck,"unit_number","—"),rate:Number(row.customer_rate),plannedMiles:Number(row.planned_miles),pickupOn:String(fees.pickup_on??""),deliveryOn:String(fees.delivery_on??""),status:fromDb[String(row.status)]??"Ready"}})}
export async function saveLoad(companyId:string,draft:LoadDraft,id?:string):Promise<LoadRecord>{const errors=validateLoad(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId);const{data,error}=await supabase.rpc("save_load",{target_company_id:companyId,target_load_id:id??null,origin_label:draft.origin,destination_label:draft.destination,customer_name:draft.customer,driver_name:draft.driver,target_unit_number:draft.unit,customer_rate_value:draft.rate,planned_miles_value:draft.plannedMiles,pickup_date:draft.pickupOn,delivery_date:draft.deliveryOn,load_status_value:toDb[draft.status]});if(error)throw new Error(error.message);const result=Array.isArray(data)?data[0]:data;if(!result)throw new Error("Load was not saved.");return{...draft,id:String(result.id),number:String(result.load_number)}}
export async function deleteLoad(companyId:string,id:string){const supabase=await context(companyId);const{error}=await supabase.from("loads").delete().eq("company_id",companyId).eq("id",id);if(error)throw new Error(error.message)}
