"use server";
import {readQueryRows} from "@/lib/read-query-rows";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from "@/lib/supabase/server";
import {validateWorkOrder,WorkOrder,WorkOrderDraft} from "@/lib/maintenance";
const toDb:Record<WorkOrderDraft["status"],string>={Scheduled:"scheduled","In progress":"in_progress",Completed:"completed",Cancelled:"cancelled"},fromDb:Record<string,WorkOrderDraft["status"]>={scheduled:"Scheduled",in_progress:"In progress",completed:"Completed",cancelled:"Cancelled"};
async function context(companyId:string){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator","fleet_manager"].includes(String(m.role)))throw new Error("Maintenance access required.");return s}
export async function listWorkOrders(companyId:string):Promise<WorkOrder[]>{const s=await context(companyId),{data,error}=await readQueryRows(offset=>s.from("work_orders").select("id,issue,status,opened_at,completed_at,details,truck:trucks(unit_number),vendor:vendors(name)").eq("company_id",companyId).order("opened_at",{ascending:false}).order("id").range(offset,offset+499));if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({id:x.id,reference:String(x.details?.reference??x.id),unit:String(x.truck?.unit_number??""),serviceType:x.details?.serviceType??"Other",description:x.issue,vendor:String(x.vendor?.name??""),scheduledDate:String(x.details?.scheduledDate??x.opened_at).slice(0,10),odometer:Number(x.details?.odometer??0),estimatedCost:Number(x.details?.estimatedCost??0),actualCost:Number(x.details?.actualCost??0),status:fromDb[x.status]??"Scheduled",completedDate:x.completed_at?String(x.completed_at).slice(0,10):""}))}
export async function saveWorkOrder(companyId:string,draft:WorkOrderDraft,records:WorkOrder[],id?:string){const e=validateWorkOrder(draft,records,id);if(Object.keys(e).length)throw new Error(Object.values(e)[0]);const s=await context(companyId),{data,error}=await s.rpc("save_work_order",{target_company_id:companyId,target_order_id:id??null,reference_value:draft.reference,target_unit_number:draft.unit,service_type_value:draft.serviceType,description_value:draft.description,vendor_name:draft.vendor,scheduled_on:draft.scheduledDate,odometer_value:draft.odometer,estimated_cost_value:draft.estimatedCost,actual_cost_value:draft.actualCost,status_value:toDb[draft.status],completed_on:draft.completedDate||null});if(error)throw new Error(error.message);return{...draft,id:String(data)}}
export async function deleteWorkOrder(companyId:string,id:string){const s=await context(companyId),{error}=await s.from("work_orders").delete().eq("company_id",companyId).eq("id",id);if(error)throw new Error(error.message)}
