"use server";
import {createClient} from "@/lib/supabase/server";
import {VendorBill,VendorBillDraft,VendorBillStatus,VendorBillPaymentDraft,validateVendorBill,validateVendorBillPayment,billOutstanding} from "@/lib/payables";

const toDb:Record<VendorBillStatus,string>={Draft:"draft",Open:"open",Paid:"paid",Void:"void"};
const fromDb:Record<string,VendorBillStatus>={draft:"Draft",open:"Open",paid:"Paid",void:"Void"};
async function context(companyId:string,write=false){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const{data:membership}=await supabase.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();const allowed=write?["owner","administrator","accountant"]:["owner","administrator","accountant","auditor"];if(!membership||!allowed.includes(String(membership.role)))throw new Error(write?"Finance access required.":"Payables access required.");return supabase}
function vendorName(value:unknown){if(Array.isArray(value))return String(value[0]?.name??"Vendor");if(value&&typeof value==="object"&&"name" in value)return String(value.name);return"Vendor"}
function mapBill(row:Record<string,unknown>):VendorBill{return{id:String(row.id),vendor:vendorName(row.vendor),billNumber:String(row.bill_number),issuedOn:String(row.issued_on),dueOn:String(row.due_on),status:fromDb[String(row.status)]??"Draft",amount:Number(row.amount),description:String(row.description??""),payments:(Array.isArray(row.payments)?row.payments:[]).map(payment=>{const value=payment as Record<string,unknown>;return{id:String(value.id),paidOn:String(value.paid_on),amount:Number(value.amount),reference:String(value.reference??"")}}).sort((a,b)=>a.paidOn.localeCompare(b.paidOn))}}
const selection="id,bill_number,issued_on,due_on,status,amount,description,vendor:vendors(name),payments:vendor_bill_payments(id,paid_on,amount,reference)";
async function getBill(companyId:string,id:string,write=false){const supabase=await context(companyId,write);const{data,error}=await supabase.from("vendor_bills").select(selection).eq("company_id",companyId).eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("Vendor bill not found.");return mapBill(data as Record<string,unknown>)}
export async function listVendorBills(companyId:string):Promise<VendorBill[]>{const supabase=await context(companyId);const{data,error}=await supabase.from("vendor_bills").select(selection).eq("company_id",companyId).order("due_on",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(row=>mapBill(row as Record<string,unknown>))}
export async function saveVendorBill(companyId:string,draft:VendorBillDraft,id?:string){const errors=validateVendorBill(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,true);const{data,error}=await supabase.rpc("save_vendor_bill",{target_company_id:companyId,target_bill_id:id??null,vendor_name:draft.vendor,bill_number_value:draft.billNumber,issued_date:draft.issuedOn,due_date:draft.dueOn,bill_status:toDb[draft.status],bill_amount:draft.amount,bill_description:draft.description});if(error)throw new Error(error.message);return getBill(companyId,String(data),true)}
export async function recordVendorBillPayment(companyId:string,billId:string,draft:VendorBillPaymentDraft){const bill=await getBill(companyId,billId,true),errors=validateVendorBillPayment(draft,billOutstanding(bill));if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,true);const{error}=await supabase.rpc("record_vendor_bill_payment",{target_company_id:companyId,target_bill_id:billId,payment_date:draft.paidOn,payment_amount:draft.amount,payment_reference:draft.reference});if(error)throw new Error(error.message);return getBill(companyId,billId,true)}
export async function deleteVendorBill(companyId:string,id:string){const supabase=await context(companyId,true);const{data,error}=await supabase.from("vendor_bills").delete().eq("company_id",companyId).eq("id",id).select("id").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("Vendor bill not found.")}
