"use server";
import {createClient} from "@/lib/supabase/server";
import {VendorBill,VendorBillAdjustment,VendorBillAdjustmentDraft,VendorBillDraft,VendorBillStatus,VendorBillPaymentDraft,validateVendorBill,validateVendorBillAdjustment,validateVendorBillPayment,billOutstanding} from "@/lib/payables";

const toDb:Record<VendorBillStatus,string>={Draft:"draft",Open:"open",Paid:"paid",Void:"void"};
const fromDb:Record<string,VendorBillStatus>={draft:"Draft",open:"Open",paid:"Paid",void:"Void"};
async function context(companyId:string,write=false){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const{data:membership}=await supabase.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();const allowed=write?["owner","administrator","accountant"]:["owner","administrator","accountant","auditor"];if(!membership||!allowed.includes(String(membership.role)))throw new Error(write?"Finance access required.":"Payables access required.");return supabase}
function vendorName(value:unknown){if(Array.isArray(value))return String(value[0]?.name??"Vendor");if(value&&typeof value==="object"&&"name" in value)return String(value.name);return"Vendor"}
function accountName(value:unknown){const account=Array.isArray(value)?value[0]:value;if(!account||typeof account!=="object")return"";const row=account as Record<string,unknown>;return`${String(row.account_number??"")} · ${String(row.name??"")}`}
function journalNumber(value:unknown){const journal=Array.isArray(value)?value[0]:value;if(!journal||typeof journal!=="object")return"";return`JE-${String((journal as Record<string,unknown>).entry_number??"")}`}
function mapBill(row:Record<string,unknown>):VendorBill{return{id:String(row.id),vendor:vendorName(row.vendor),billNumber:String(row.bill_number),issuedOn:String(row.issued_on),dueOn:String(row.due_on),status:fromDb[String(row.status)]??"Draft",amount:Number(row.amount),description:String(row.description??""),expenseAccount:accountName(row.expenseAccount),journalNumber:journalNumber(row.journal),payments:(Array.isArray(row.payments)?row.payments:[]).map(payment=>{const value=payment as Record<string,unknown>;return{id:String(value.id),paidOn:String(value.paid_on),amount:Number(value.amount),reference:String(value.reference??""),paymentAccount:accountName(value.paymentAccount),journalNumber:journalNumber(value.journal)}}).sort((a,b)=>a.paidOn.localeCompare(b.paidOn)),adjustments:(Array.isArray(row.adjustments)?row.adjustments:[]).map((adjustment):VendorBillAdjustment=>{const value=adjustment as Record<string,unknown>;return{id:String(value.id),adjustedOn:String(value.adjusted_on),type:String(value.adjustment_type)==="debit"?"Debit":"Credit",amount:Number(value.amount),reason:String(value.reason),journalNumber:journalNumber(value.journal)}}).sort((a,b)=>a.adjustedOn.localeCompare(b.adjustedOn))}}
const selection="id,bill_number,issued_on,due_on,status,amount,description,vendor:vendors(name),expenseAccount:chart_of_accounts!vendor_bills_expense_account_fk(account_number,name),journal:journal_entries!vendor_bills_journal_entry_fk(entry_number),payments:vendor_bill_payments(id,paid_on,amount,reference,paymentAccount:chart_of_accounts!vendor_bill_payments_account_fk(account_number,name),journal:journal_entries!vendor_bill_payments_journal_entry_fk(entry_number)),adjustments:vendor_bill_adjustments(id,adjusted_on,adjustment_type,amount,reason,journal:journal_entries!vendor_bill_adjustments_journal_entry_fk(entry_number))";
async function getBill(companyId:string,id:string,write=false){const supabase=await context(companyId,write);const{data,error}=await supabase.from("vendor_bills").select(selection).eq("company_id",companyId).eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("Vendor bill not found.");return mapBill(data as Record<string,unknown>)}
export async function listVendorBills(companyId:string):Promise<VendorBill[]>{const supabase=await context(companyId);const{data,error}=await supabase.from("vendor_bills").select(selection).eq("company_id",companyId).order("due_on",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map(row=>mapBill(row as Record<string,unknown>))}
export async function saveVendorBill(companyId:string,draft:VendorBillDraft,id?:string){const errors=validateVendorBill(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,true);const{data,error}=await supabase.rpc("save_vendor_bill",{target_company_id:companyId,target_bill_id:id??null,vendor_name:draft.vendor,bill_number_value:draft.billNumber,issued_date:draft.issuedOn,due_date:draft.dueOn,bill_status:toDb[draft.status],bill_amount:draft.amount,bill_description:draft.description,expense_account_text:draft.expenseAccount,paid_from_account_text:draft.paidFromAccount});if(error)throw new Error(error.message);return getBill(companyId,String(data),true)}
export async function recordVendorBillPayment(companyId:string,billId:string,draft:VendorBillPaymentDraft){const bill=await getBill(companyId,billId,true),errors=validateVendorBillPayment(draft,billOutstanding(bill));if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,true);const{error}=await supabase.rpc("record_vendor_bill_payment",{target_company_id:companyId,target_bill_id:billId,payment_date:draft.paidOn,payment_amount:draft.amount,payment_reference:draft.reference,payment_account_text:draft.paymentAccount});if(error)throw new Error(error.message);return getBill(companyId,billId,true)}
export async function recordVendorBillAdjustment(companyId:string,billId:string,draft:VendorBillAdjustmentDraft){const bill=await getBill(companyId,billId,true),adjustedTotal=bill.amount+bill.adjustments.reduce((sum,item)=>sum+(item.type==="Debit"?item.amount:-item.amount),0),errors=validateVendorBillAdjustment(draft,adjustedTotal,bill.issuedOn);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);const supabase=await context(companyId,true);const{error}=await supabase.rpc("record_vendor_bill_adjustment",{target_company_id:companyId,target_bill_id:billId,adjustment_date:draft.adjustedOn,adjustment_kind:draft.type.toLowerCase(),adjustment_amount:draft.amount,adjustment_reason:draft.reason});if(error)throw new Error(error.message);return getBill(companyId,billId,true)}
export async function voidVendorBill(companyId:string,billId:string,reversalDate:string){if(!reversalDate)throw new Error("Choose a reversal date.");const supabase=await context(companyId,true);const{error}=await supabase.rpc("void_vendor_bill",{target_company_id:companyId,target_bill_id:billId,reversal_date:reversalDate});if(error)throw new Error(error.message);return getBill(companyId,billId,true)}
export async function deleteVendorBill(companyId:string,id:string){const supabase=await context(companyId,true);const{data,error}=await supabase.from("vendor_bills").delete().eq("company_id",companyId).eq("id",id).select("id").maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("Vendor bill not found.")}
