"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from "@/lib/supabase/server";
import {Settlement,SettlementDraft,validateSettlement} from "@/lib/payroll";
const toDb:Record<SettlementDraft["status"],string>={Draft:"draft",Approved:"approved",Paid:"posted"},fromDb:Record<string,SettlementDraft["status"]>={draft:"Draft",approved:"Approved",posted:"Paid"};
async function context(companyId:string){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator","payroll_manager"].includes(String(m.role)))throw new Error("Payroll access required.");return s}
export async function listSettlements(companyId:string):Promise<Settlement[]>{const s=await context(companyId),{data,error}=await s.from("driver_settlements").select("id,gross_pay,authorized_deductions,reimbursements,status,details,paid_on,driver:drivers(profile:profiles(full_name)),period:payroll_periods(starts_on,ends_on)").eq("company_id",companyId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>{const d=Array.isArray(x.driver)?x.driver[0]:x.driver,p=Array.isArray(d?.profile)?d.profile[0]:d?.profile,period=Array.isArray(x.period)?x.period[0]:x.period;return{id:x.id,driver:String(p?.full_name??"Unknown driver"),periodStart:String(period?.starts_on??""),periodEnd:String(period?.ends_on??""),loads:Number(x.details?.loads??0),grossPay:Number(x.gross_pay),reimbursements:Number(x.reimbursements),deductions:Number(x.authorized_deductions),status:fromDb[x.status]??"Draft",paidDate:String(x.paid_on??"")}})}
export async function saveSettlement(companyId:string,draft:SettlementDraft,id?:string):Promise<Settlement>{const e=validateSettlement(draft);if(Object.keys(e).length)throw new Error(Object.values(e)[0]);const s=await context(companyId),{data,error}=await s.rpc("save_driver_settlement",{target_company_id:companyId,target_settlement_id:id??null,driver_name:draft.driver,period_start:draft.periodStart,period_end:draft.periodEnd,load_count:draft.loads,gross_pay_value:draft.grossPay,reimbursements_value:draft.reimbursements,deductions_value:draft.deductions,status_value:toDb[draft.status],paid_date:draft.paidDate||null});if(error)throw new Error(error.message);return{...draft,id:String(data)}}
export async function deleteSettlement(companyId:string,id:string){const s=await context(companyId),{error}=await s.rpc("delete_driver_settlement",{target_company_id:companyId,target_settlement_id:id});if(error)throw new Error(error.message)}
