"use server";
import {readQueryRows} from "@/lib/read-query-rows";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {MemberDraft,TeamMember,validateMember} from "@/lib/team";
async function context(companyId:string){const s=await createClient();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.getClaims(),uid=data?.claims?.sub;if(error||typeof uid!=="string")throw new Error("Authentication required.");const{data:m}=await s.from("company_memberships").select("role").eq("company_id",companyId).eq("user_id",uid).eq("is_active",true).maybeSingle();if(!m||!["owner","administrator"].includes(String(m.role)))throw new Error("Team administration access required.");return{s,role:String(m.role)}}
const statusMap:Record<string,TeamMember["status"]>={invited:"Invited",active:"Active",suspended:"Suspended"};
export async function listTeamMembers(companyId:string):Promise<TeamMember[]>{const{s}=await context(companyId),{data,error}=await readQueryRows(offset=>s.from("company_memberships").select("id,role,is_active,membership_status,display_name,email,created_at,updated_at,profile:profiles(full_name)").eq("company_id",companyId).order("created_at").order("id").range(offset,offset+499));if(error)throw new Error(error.message);return(data??[]).map((x:any)=>{const p=Array.isArray(x.profile)?x.profile[0]:x.profile;return{id:x.id,name:x.display_name||p?.full_name||"Team member",email:x.email||"",role:x.role,status:statusMap[x.membership_status]??(x.is_active?"Active":"Suspended"),invitedAt:x.created_at,lastActive:x.updated_at}})}
export async function inviteTeamMember(companyId:string,draft:MemberDraft,members:TeamMember[]){const e=validateMember(draft,members);if(Object.keys(e).length)throw new Error(Object.values(e)[0]);const{role}=await context(companyId);if(role!=="owner"&&draft.role==="owner")throw new Error("Only owners can invite another owner.");const admin=createAdminClient();if(!admin)throw new Error("Team invitations require SUPABASE_SERVICE_ROLE_KEY on the server.");const{data,error}=await admin.auth.admin.inviteUserByEmail(draft.email,{data:{full_name:draft.name}});if(error)throw new Error(error.message);if(!data.user)throw new Error("Invitation did not create a user.");const{data:membership,error:membershipError}=await admin.from("company_memberships").insert({company_id:companyId,user_id:data.user.id,role:draft.role,is_active:draft.status==="Active",membership_status:draft.status.toLowerCase(),display_name:draft.name.trim(),email:draft.email.trim().toLowerCase()}).select("id,created_at,updated_at").single();if(membershipError)throw new Error(membershipError.message);return{...draft,id:membership.id,invitedAt:membership.created_at,lastActive:membership.updated_at}}
export async function updateTeamMember(companyId:string,draft:MemberDraft,id:string){const{s}=await context(companyId),{error}=await s.rpc("update_company_member",{target_company_id:companyId,target_membership_id:id,display_name_value:draft.name,email_value:draft.email,role_value:draft.role,status_value:draft.status.toLowerCase()});if(error)throw new Error(error.message);return{...draft,id,invitedAt:"",lastActive:new Date().toISOString()}}
export async function removeTeamMember(companyId:string,id:string){const{s}=await context(companyId),{error}=await s.rpc("remove_company_member",{target_company_id:companyId,target_membership_id:id});if(error)throw new Error(error.message)}
export async function resendTeamInvitation(companyId:string,id:string){const{s}=await context(companyId),{data:member,error:memberError}=await s.from("company_memberships").select("email,membership_status").eq("company_id",companyId).eq("id",id).single();if(memberError)throw new Error(memberError.message);if(member.membership_status!=="invited"||!member.email)throw new Error("Only pending invitations can be resent.");const{error}=await s.auth.resend({type:"signup",email:member.email});if(error)throw new Error(error.message)}
