"use server";
import {createClient} from "@/lib/supabase/server";
import {Transaction,TransactionDraft,TransactionStatus,validateTransaction} from "@/lib/transactions";
const toDbStatus:Record<TransactionStatus,string>={"Needs review":"pending",Matched:"approved",Scheduled:"draft",Paid:"posted"};
const fromDbStatus:Record<string,TransactionStatus>={pending:"Needs review",approved:"Matched",draft:"Scheduled",posted:"Paid",rejected:"Needs review",void:"Needs review"};
async function context(companyId:string){const supabase=await createClient();if(!supabase)throw new Error("Supabase is not configured.");const {data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;if(error||typeof userId!=="string")throw new Error("Authentication required.");const {data:membership}=await supabase.from("company_memberships").select("company_id").eq("company_id",companyId).eq("user_id",userId).eq("is_active",true).maybeSingle();if(!membership)throw new Error("Company access denied.");return{supabase,userId}}
export async function listTransactions(companyId:string):Promise<Transaction[]>{const{supabase}=await context(companyId);const [expenses,income]=await Promise.all([supabase.from("expenses").select("id,occurred_on,description,amount,status,vendor:vendors(name)").eq("company_id",companyId),supabase.from("income").select("id,received_on,description,amount,status,customer:customers(name)").eq("company_id",companyId)]);if(expenses.error)throw new Error(expenses.error.message);if(income.error)throw new Error(income.error.message);const expenseRows=(expenses.data??[]).map((x)=>({id:`expense:${x.id}`,occurredOn:String(x.occurred_on),payee:relationName(x.vendor,"Expense vendor"),description:String(x.description),amount:Number(x.amount),kind:"expense" as const,status:fromDbStatus[String(x.status)]??"Needs review"}));const incomeRows=(income.data??[]).map((x)=>({id:`income:${x.id}`,occurredOn:String(x.received_on),payee:relationName(x.customer,"Income customer"),description:String(x.description),amount:Number(x.amount),kind:"income" as const,status:fromDbStatus[String(x.status)]??"Needs review"}));return [...expenseRows,...incomeRows].sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn))}
function relationName(value:unknown,fallback:string){if(Array.isArray(value))return String(value[0]?.name??fallback);if(value&&typeof value==="object"&&"name" in value)return String(value.name);return fallback}
export async function saveTransaction(companyId:string,draft:TransactionDraft,recordId?:string):Promise<Transaction>{
 const errors=validateTransaction(draft);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);
 const{supabase}=await context(companyId);const[previousKind,rawId]=recordId?.split(":")??[];
 if(recordId&&(!rawId||!["income","expense"].includes(previousKind)))throw new Error("Invalid transaction reference.");
 const{data,error}=await supabase.rpc("save_transaction",{target_company_id:companyId,target_record_id:rawId??null,previous_kind:previousKind??null,new_kind:draft.kind,transaction_date:draft.occurredOn,partner_name:draft.payee,description_value:draft.description,amount_value:draft.amount,status_value:toDbStatus[draft.status]});
 if(error)throw new Error(error.message);return{...draft,id:`${draft.kind}:${data}`};
}
export async function deleteTransaction(companyId:string,recordId:string){const{supabase}=await context(companyId);const[kind,id]=recordId.split(":");if(!id||!['income','expense'].includes(kind))throw new Error("Invalid transaction reference.");const {error}=await supabase.from(kind==="income"?"income":"expenses").delete().eq("company_id",companyId).eq("id",id);if(error)throw new Error(error.message)}
