"use client";
import {useEffect,useState} from "react";
import {disconnectBusinessEmail,loadBusinessEmailSettings,saveBusinessEmailSettings} from "@/app/actions/invoice-delivery";
export function BusinessEmailSettings({companyId}:{companyId:string}){
 const [senderEmail,setSenderEmail]=useState(""),[senderName,setSenderName]=useState(""),[apiKey,setApiKey]=useState(""),[configured,setConfigured]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;loadBusinessEmailSettings(companyId).then(value=>{if(active){setSenderEmail(value.senderEmail);setSenderName(value.senderName);setConfigured(value.configured);setLoaded(true);setError("")}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load email setup.")});return()=>{active=false}},[companyId,reload]);
 async function save(disconnect=false){if(busy||!loaded)return;setBusy(true);setError("");setNotice("");try{
  if(disconnect){await disconnectBusinessEmail(companyId);setConfigured(false);setNotice("Email disconnected.")}else{await saveBusinessEmailSettings(companyId,{senderEmail,senderName,apiKey});setConfigured(true);setNotice("Email setup saved. Verify your sender domain in Resend before sending invoices.")}
  setApiKey("");
 }catch(cause){setError(cause instanceof Error?cause.message:"Unable to save email setup.")}finally{setBusy(false)}}
 return <section className="mt-5 rounded-xl border border-[var(--line)] p-4" aria-label="Business invoice email"><h3 className="font-bold">Business invoice email</h3><p className="mt-2 text-sm text-[var(--muted)]">Connect your Resend account and verified sender to send invoice PDFs from Invoices. Owner or administrator access is required. Automatic reminders are separate.</p>
  {error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-[var(--teal)]">{notice}</p>}
  {!loaded?<button type="button" className="mt-3 rounded-xl border px-3 py-2" onClick={()=>setReload(x=>x+1)}>{error?"Retry email setup":"Loading email setup…"}</button>:<fieldset disabled={busy} className="mt-4 space-y-3"><p className="text-sm font-bold">{configured?"Sender configured":"Sender not connected"}</p><label className="block text-sm font-bold">Sender name<input className="input" value={senderName} onChange={event=>setSenderName(event.target.value)} maxLength={100}/></label><label className="block text-sm font-bold">Sender email<input type="email" className="input" value={senderEmail} onChange={event=>setSenderEmail(event.target.value)}/></label><label className="block text-sm font-bold">Resend API key<input type="password" autoComplete="new-password" className="input" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={configured?"Leave blank to keep the saved key":"re_…"}/></label><p className="text-xs text-[var(--muted)]">The key is encrypted on the server and is never returned to this form.</p><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void save()} className="rounded-xl bg-[var(--teal)] px-4 py-3 font-bold text-white">{busy?"Saving…":"Save email setup"}</button>{configured&&<button type="button" onClick={()=>{if(confirm("Disconnect invoice email for this business?"))void save(true)}} className="rounded-xl border px-4 py-3">Disconnect email</button>}</div></fieldset>}
 </section>;
}
